### ISSUE TITLE
fast/block/nested-renderers.html fails

### ISSUE THREAD

**Issue by annulen** [annulen/webkit#217]

**Comment by annulen** [comment]
In debug assertion fails:
```
STDERR: ASSERTION FAILED: !current.renderer()
```
```
#0  WTFCrash () at ../../Source/WTF/wtf/Assertions.cpp:322
#1  0x00007fd18fd52649 in WebCore::Style::resetStyleForNonRenderedDescendants (current=...) at ../../Source/WebCore/style/StyleTreeResolver.cpp:443
#2  0x00007fd18fd54156 in WebCore::Style::TreeResolver::resolveComposedTree (this=0x7fffdbffaba8) at ../../Source/WebCore/style/StyleTreeResolver.cpp:888
#3  0x00007fd18fd548d7 in WebCore::Style::TreeResolver::resolve (this=0x7fffdbffaba8, change=WebCore::Style::Force) at ../../Source/WebCore/style/StyleTreeResolver.cpp:978
#4  0x00007fd18f2cc5c7 in WebCore::Document::recalcStyle (this=0x7fd180ae9000, change=WebCore::Style::Force) at ../../Source/WebCore/dom/Document.cpp:1889
#5  0x00007fd18f2c117d in WebCore::Document::updateStyleIfNeeded (this=0x7fd180ae9000) at ../../Source/WebCore/dom/Document.cpp:1940
#6  0x00007fd18f3d17a9 in std::_Mem_fn<void (WebCore::Document::*)()>::operator()<, void>(WebCore::Document*) const (this=0x337faa0, __object=0x7fd180ae9000) at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/functional:601
#7  0x00007fd18f3d1730 in std::_Bind<std::_Mem_fn<void (WebCore::Document::*)()> (WebCore::Document*)>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (this=0x337faa0, __args=<unknown type in /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/Debug/lib/libQt5WebKit.so.5, CU 0x0, DIE 0x351b5e>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/functional:1295
#8  0x00007fd18f3d16c6 in std::_Bind<std::_Mem_fn<void (WebCore::Document::*)()> (WebCore::Document*)>::operator()<, void>() (this=0x337faa0) at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/functional:1353
#9  0x00007fd18f3d13ad in std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (WebCore::Document::*)()> (WebCore::Document*)> >::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/functional:2071
#10 0x00000000004bce2e in std::function<void ()>::operator()() const (this=0x7fd180ae9538) at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/functional:2471
#11 0x00007fd18daf3899 in WebCore::Timer::fired (this=0x7fd180ae9500) at ../../Source/WebCore/platform/Timer.h:133
#12 0x00007fd18fbf160a in WebCore::ThreadTimers::sharedTimerFiredInternal (this=0x7fd180bfc078) at ../../Source/WebCore/platform/ThreadTimers.cpp:121
#13 0x00007fd18fbf18c1 in WebCore::ThreadTimers::setSharedTimer(WebCore::SharedTimer*)::$_0::operator()() const (this=0x3426dc0) at ../../Source/WebCore/platform/ThreadTimers.cpp:73
#14 0x00007fd18fbf173d in std::_Function_handler<void (), WebCore::ThreadTimers::setSharedTimer(WebCore::SharedTimer*)::$_0>::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/functional:2071
#15 0x00000000004bce2e in std::function<void ()>::operator()() const (this=0x7fd192e42500 <WebCore::MainThreadSharedTimer::singleton()::instance+8>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/functional:2471
#16 0x00007fd1906905e5 in WebCore::MainThreadSharedTimer::fired (this=0x7fd192e424f8 <WebCore::MainThreadSharedTimer::singleton()::instance>) at ../../Source/WebCore/platform/MainThreadSharedTimer.cpp:52
#17 0x00007fd19073cf71 in WebCore::SharedTimerQt::timerEvent (this=0x3421210, ev=0x7fffdbffb860) at ../../Source/WebCore/platform/qt/MainThreadSharedTimerQt.cpp:107
#18 0x00007fd18889eebc in QObject::event(QEvent*) () from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/DependenciesQT/Root/lib/libQt5Core.so.5
#19 0x00007fd18d007fec in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/DependenciesQT/Root/lib/libQt5Widgets.so.5
#20 0x00007fd18d00d000 in QApplication::notify(QObject*, QEvent*) () from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/DependenciesQT/Root/lib/libQt5Widgets.so.5
#21 0x00007fd18886ea25 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/DependenciesQT/Root/lib/libQt5Core.so.5
#22 0x00007fd1888c580d in QTimerInfoList::activateTimers() () from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/DependenciesQT/Root/lib/libQt5Core.so.5
#23 0x00007fd1888c5b31 in ?? () from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/DependenciesQT/Root/lib/libQt5Core.so.5
#24 0x00007fd18aa15d74 in g_main_dispatch (context=0x3414140) at gmain.c:3122
#25 g_main_context_dispatch (context=context@entry=0x3414140) at gmain.c:3737
#26 0x00007fd18aa15fc8 in g_main_context_iterate (context=context@entry=0x3414140, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3808
#27 0x00007fd18aa1606c in g_main_context_iteration (context=0x3414140, may_block=1) at gmain.c:3869
#28 0x00007fd1888c5dfc in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/DependenciesQT/Root/lib/libQt5Core.so.5
#29 0x00007fd18886c97b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/DependenciesQT/Root/lib/libQt5Core.so.5
#30 0x00007fd188874006 in QCoreApplication::exec() () from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/DependenciesQT/Root/lib/libQt5Core.so.5
#31 0x000000000045df44 in main (argc=2, argv=0x7fffdbffbeb8) at ../../Tools/DumpRenderTree/qt/DumpRenderTreeMain.cpp:201
```
