### ISSUE TITLE
fast/forms/datalist/datalist-child-validation.html - ASSERTION FAILED: m_isValid == valid()

### ISSUE THREAD

**Issue by annulen** [annulen/webkit#260]
```diff
diff --git a/Source/WebCore/html/HTMLFormControlElement.cpp b/Source/WebCore/html/HTMLFormControlElement.cpp
index 664c420..c883054 100644
--- a/Source/WebCore/html/HTMLFormControlElement.cpp
+++ b/Source/WebCore/html/HTMLFormControlElement.cpp
@@ -390,6 +390,7 @@ bool HTMLFormControlElement::matchesValidPseudoClass() const
 
 bool HTMLFormControlElement::matchesInvalidPseudoClass() const
 {
+    const_cast<HTMLFormControlElement*>(this)->updateValidity();
     return willValidate() && !isValidFormControlElement();
 }
 ```

**Comment by annulen** [comment]
```
#0  WTFCrash () at ../../Source/WTF/wtf/Assertions.cpp:322
#1  0x00007fbfd9b94d8d in WebCore::HTMLFormControlElement::isValidFormControlElement (this=0x7fbfcb5bf2e8) at ../../Source/WebCore/html/HTMLFormControlElement.cpp:494
#2  0x00007fbfd9b2c026 in WebCore::HTMLFormControlElement::matchesInvalidPseudoClass (this=0x7fbfcb5bf2e8) at ../../Source/WebCore/html/HTMLFormControlElement.cpp:393
#3  0x00007fbfd9ffab29 in WebCore::isInvalid (element=...) at ../../Source/WebCore/css/SelectorCheckerTestFunctions.h:98
#4  0x00007fbfd9f9af8a in WebCore::SelectorChecker::checkOne (this=0x7ffe311979e8, checkingContext=..., context=..., dynamicPseudoIdSet=..., matchType=@0x7ffe311977ec: WebCore::SelectorChecker::Element, specificity=@0x7ffe31197920: 256) at ../../Source/WebCore/css/SelectorChecker.cpp:946
#5  0x00007fbfd9f990f1 in WebCore::SelectorChecker::matchRecursively (this=0x7ffe311979e8, checkingContext=..., context=..., dynamicPseudoIdSet=..., specificity=@0x7ffe31197920: 256) at ../../Source/WebCore/css/SelectorChecker.cpp:234
#6  0x00007fbfd9f98f82 in WebCore::SelectorChecker::match (this=0x7ffe311979e8, selector=..., element=..., checkingContext=..., specificity=@0x7ffe31197920: 256) at ../../Source/WebCore/css/SelectorChecker.cpp:183
#7  0x00007fbfd9dfb453 in WebCore::SelectorDataList::selectorMatches (this=0x7fbfcb5147e8, selectorData=..., element=..., rootNode=...) at ../../Source/WebCore/dom/SelectorQuery.cpp:121
#8  0x00007fbfd9eb8598 in WebCore::SelectorDataList::executeSingleSelectorData<WebCore::SingleElementExtractorSelectorQueryTrait> (this=0x7fbfcb5147e8, rootNode=..., searchRootNode=..., selectorData=..., output=@0x7ffe31197cb8: 0x0) at ../../Source/WebCore/dom/SelectorQuery.cpp:373
#9  0x00007fbfd9dfbb13 in WebCore::SelectorDataList::execute<WebCore::SingleElementExtractorSelectorQueryTrait> (this=0x7fbfcb5147e8, rootNode=..., output=@0x7ffe31197cb8: 0x0) at ../../Source/WebCore/dom/SelectorQuery.cpp:564
#10 0x00007fbfd9db5eb9 in WebCore::SelectorDataList::queryFirst (this=0x7fbfcb5147e8, rootNode=...) at ../../Source/WebCore/dom/SelectorQuery.cpp:185
#11 0x00007fbfd9dd179c in WebCore::SelectorQuery::queryFirst (this=0x7fbfcb5147e0, rootNode=...) at ../../Source/WebCore/dom/SelectorQuery.h:158
#12 0x00007fbfd9d31b43 in WebCore::ContainerNode::querySelector (this=0x7fbfcb529680, selectors=..., ec=@0x7ffe31197df4: 0) at ../../Source/WebCore/dom/ContainerNode.cpp:839
#13 0x00007fbfdaa94e7b in WebCore::jsElementPrototypeFunctionQuerySelector (state=0x7ffe31197e40) at DerivedSources/WebCore/JSElement.cpp:4864
#14 0x00007fbf8b3ff028 in ?? ()
#15 0x00007ffe31197eb0 in ?? ()
#16 0x00000000004fec4d in llint_entry ()
```
