### ISSUE TITLE
css3/masking/mask-svg-script-none-to-png.html crashes

### ISSUE THREAD

**Issue by annulen** [annulen/webkit#280]
```
Thread 1 (Thread 0x7f6c6304b7c0 (LWP 8295)):
#0  0x00007f6c58adaffe in ?? () from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/DependenciesQT/Root/lib/libQt5Gui.so.5
#1  0x00007f6c5785c1a9 in __run_exit_handlers (status=139, listp=0x7f6c57bde6c8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true) at exit.c:82
#2  0x00007f6c5785c1f5 in __GI_exit (status=<optimized out>) at exit.c:104
#3  0x000000000138ebae in dumpBacktraceSignalHandler (sig=11) at ../../Source/WTF/wtf/Assertions.cpp:349
#4  <signal handler called>
#5  0x00007f6c58a88e3c in QPixmap::hasAlpha() const () from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/DependenciesQT/Root/lib/libQt5Gui.so.5
#6  0x00007f6c5fcaec32 in WebCore::GraphicsContext::drawPattern (this=0x7ffeb03fe5c8, image=..., tileRect=..., patternTransform=..., phase=..., spacing=..., op=WebCore::CompositeSourceOver, destRect=..., blendMode=WebCore::BlendModeNormal) at ../../Source/WebCore/platform/graphics/qt/GraphicsContextQt.cpp:533
#7  0x00007f6c5fcc240e in WebCore::Image::drawPattern (this=0x7f6c50919630, ctxt=..., tileRect=..., patternTransform=..., phase=..., spacing=..., op=WebCore::CompositeSourceOver, destRect=..., blendMode=WebCore::BlendModeNormal) at ../../Source/WebCore/platform/graphics/qt/ImageQt.cpp:138
#8  0x00007f6c5faa6476 in WebCore::BitmapImage::drawPattern (this=0x7f6c509f4898, ctxt=..., tileRect=..., transform=..., phase=..., spacing=..., op=WebCore::CompositeSourceOver, destRect=..., blendMode=WebCore::BlendModeNormal) at ../../Source/WebCore/platform/graphics/BitmapImage.cpp:629
#9  0x00007f6c5fb09cb1 in WebCore::Image::drawTiled (this=0x7f6c509f4898, ctxt=..., destRect=..., srcPoint=..., scaledTileSize=..., spacing=..., op=WebCore::CompositeSourceOver, blendMode=WebCore::BlendModeNormal) at ../../Source/WebCore/platform/graphics/Image.cpp:194
#10 0x00007f6c5faf7654 in WebCore::GraphicsContext::drawTiledImage (this=0x7ffeb03fe5c8, image=..., destination=..., source=..., tileSize=..., spacing=..., imagePaintingOptions=...) at ../../Source/WebCore/platform/graphics/GraphicsContext.cpp:761
#11 0x00007f6c5ea6523c in WebCore::RenderBoxModelObject::paintFillLayerExtended (this=0x7f6c509f2958, paintInfo=..., color=..., bgLayer=0x7f6c509a6598, rect=..., bleedAvoidance=WebCore::BackgroundBleedNone, box=0x0, boxSize=..., op=WebCore::CompositeSourceOver, backgroundObject=0x0, baseBgColorUsage=WebCore::BaseBackgroundColorUse) at ../../Source/WebCore/rendering/RenderBoxModelObject.cpp:839
#12 0x00007f6c5eace8dc in WebCore::RenderBox::paintFillLayer (this=0x7f6c509f2958, paintInfo=..., c=..., fillLayer=0x7f6c509a6598, rect=..., bleedAvoidance=WebCore::BackgroundBleedNone, op=WebCore::CompositeSourceOver, backgroundObject=0x0, baseBgColorUsage=WebCore::BaseBackgroundColorUse) at ../../Source/WebCore/rendering/RenderBox.cpp:1669
#13 0x00007f6c5eac9092 in WebCore::RenderBox::paintFillLayers (this=0x7f6c509f2958, paintInfo=..., c=..., fillLayer=0x7f6c509a6598, rect=..., bleedAvoidance=WebCore::BackgroundBleedNone, op=WebCore::CompositeSourceOver, backgroundObject=0x0) at ../../Source/WebCore/rendering/RenderBox.cpp:1660
#14 0x00007f6c5eace4c0 in WebCore::RenderBox::paintMaskImages (this=0x7f6c509f2958, paintInfo=..., paintRect=...) at ../../Source/WebCore/rendering/RenderBox.cpp:1593
#15 0x00007f6c5eace2ca in WebCore::RenderBox::paintMask (this=0x7f6c509f2958, paintInfo=..., paintOffset=...) at ../../Source/WebCore/rendering/RenderBox.cpp:1553
#16 0x00007f6c5ea825ed in WebCore::RenderBlock::paintObject (this=0x7f6c509f2958, paintInfo=..., paintOffset=...) at ../../Source/WebCore/rendering/RenderBlock.cpp:1571
#17 0x00007f6c5ea80def in WebCore::RenderBlock::paint (this=0x7f6c509f2958, paintInfo=..., paintOffset=...) at ../../Source/WebCore/rendering/RenderBlock.cpp:1430
#18 0x00007f6c5eb57d17 in WebCore::RenderLayer::paintMaskForFragments (this=0x7f6c509d7360, layerFragments=..., context=..., localPaintingInfo=..., subtreePaintRootForRenderer=0x0) at ../../Source/WebCore/rendering/RenderLayer.cpp:4772
#19 0x00007f6c5eb53a11 in WebCore::RenderLayer::paintLayerContents (this=0x7f6c509d7360, originalContext=..., paintingInfo=..., paintFlags=97) at ../../Source/WebCore/rendering/RenderLayer.cpp:4377
#20 0x00007f6c5eb52d45 in WebCore::RenderLayer::paintLayerContentsAndReflection (this=0x7f6c509d7360, context=..., paintingInfo=..., paintFlags=97) at ../../Source/WebCore/rendering/RenderLayer.cpp:3998
#21 0x00007f6c5eb51963 in WebCore::RenderLayer::paintLayer (this=0x7f6c509d7360, context=..., paintingInfo=..., paintFlags=97) at ../../Source/WebCore/rendering/RenderLayer.cpp:3980
#22 0x00007f6c5eb56fe4 in WebCore::RenderLayer::paintList (this=0x7f6c509d7d80, list=0x7f6c50916100, context=..., paintingInfo=..., paintFlags=96) at ../../Source/WebCore/rendering/RenderLayer.cpp:4448
#23 0x00007f6c5eb53802 in WebCore::RenderLayer::paintLayerContents (this=0x7f6c509d7d80, originalContext=..., paintingInfo=..., paintFlags=96) at ../../Source/WebCore/rendering/RenderLayer.cpp:4353
#24 0x00007f6c5eb52d45 in WebCore::RenderLayer::paintLayerContentsAndReflection (this=0x7f6c509d7d80, context=..., paintingInfo=..., paintFlags=96) at ../../Source/WebCore/rendering/RenderLayer.cpp:3998
#25 0x00007f6c5eb51963 in WebCore::RenderLayer::paintLayer (this=0x7f6c509d7d80, context=..., paintingInfo=..., paintFlags=96) at ../../Source/WebCore/rendering/RenderLayer.cpp:3980
#26 0x00007f6c5eb56fe4 in WebCore::RenderLayer::paintList (this=0x7f6c509d77e0, list=0x7f6c509160f0, context=..., paintingInfo=..., paintFlags=96) at ../../Source/WebCore/rendering/RenderLayer.cpp:4448
#27 0x00007f6c5eb53802 in WebCore::RenderLayer::paintLayerContents (this=0x7f6c509d77e0, originalContext=..., paintingInfo=..., paintFlags=96) at ../../Source/WebCore/rendering/RenderLayer.cpp:4353
#28 0x00007f6c5eb52d45 in WebCore::RenderLayer::paintLayerContentsAndReflection (this=0x7f6c509d77e0, context=..., paintingInfo=..., paintFlags=0) at ../../Source/WebCore/rendering/RenderLayer.cpp:3998
#29 0x00007f6c5eb51963 in WebCore::RenderLayer::paintLayer (this=0x7f6c509d77e0, context=..., paintingInfo=..., paintFlags=0) at ../../Source/WebCore/rendering/RenderLayer.cpp:3980
#30 0x00007f6c5eb5122b in WebCore::RenderLayer::paint (this=0x7f6c509d77e0, context=..., damageRect=..., subpixelAccumulation=..., paintBehavior=0, subtreePaintRoot=0x0, paintFlags=0) at ../../Source/WebCore/rendering/RenderLayer.cpp:3784
#31 0x00007f6c5f98649c in WebCore::FrameView::paintContents (this=0x7f6c0c5f3680, context=..., dirtyRect=...) at ../../Source/WebCore/page/FrameView.cpp:4090
#32 0x00007f6c5d9fe6d6 in QWebFrameAdapter::renderRelativeCoords (this=0x3792b80, painter=0x7ffeb03febc0, layers=255, clip=...) at ../../Source/WebKit/qt/WebCoreSupport/QWebFrameAdapter.cpp:547
#33 0x00007f6c63142a57 in QWebFrame::render (this=0x3792ab0, painter=0x7ffeb03febc0, layer=..., clip=...) at ../../Source/WebKit/qt/WidgetApi/qwebframe.cpp:646
#34 0x00007f6c63142aeb in QWebFrame::render (this=0x3792ab0, painter=0x7ffeb03febc0, clip=...) at ../../Source/WebKit/qt/WidgetApi/qwebframe.cpp:654
#35 0x0000000000467572 in DumpRenderTree::dump (this=0x7ffeb0400310) at ../../Tools/DumpRenderTree/qt/DumpRenderTreeQt.cpp:1017
#36 0x0000000000480400 in DumpRenderTree::qt_static_metacall (_o=0x7ffeb0400310, _c=QMetaObject::InvokeMetaMethod, _id=5, _a=0x7ffeb03fedf0) at Tools/DumpRenderTree/moc_DumpRenderTreeQt.cpp:144
#37 0x00007f6c586fd2c1 in QMetaObject::activate(QObject*, int, int, void**) () from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/DependenciesQT/Root/lib/libQt5Core.so.5
#38 0x0000000000482092 in TestRunnerQt::done (this=0x37949b0) at Tools/DumpRenderTree/moc_TestRunnerQt.cpp:715
#39 0x0000000000477b8b in TestRunnerQt::maybeDump (this=0x37949b0) at ../../Tools/DumpRenderTree/qt/TestRunnerQt.cpp:143
#40 0x0000000000481143 in TestRunnerQt::qt_static_metacall (_o=0x37949b0, _c=QMetaObject::InvokeMetaMethod, _id=4, _a=0x7ffeb03ff160) at Tools/DumpRenderTree/moc_TestRunnerQt.cpp:491
#41 0x00007f6c586fd2c1 in QMetaObject::activate(QObject*, int, int, void**) () from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/DependenciesQT/Root/lib/libQt5Core.so.5
#42 0x00007f6c6315101d in QWebPage::loadFinished (this=0x37991e0, _t1=true) at Source/WebKit/moc_qwebpage.cpp:846
#43 0x00007f6c63141c4f in QWebFramePrivate::emitLoadFinished (this=0x3792b80, originatingLoad=true, ok=true) at ../../Source/WebKit/qt/WidgetApi/qwebframe.cpp:112
#44 0x00007f6c5d9c89f8 in WebCore::FrameLoaderClientQt::emitLoadFinished (this=0x3798750, ok=true) at ../../Source/WebKit/qt/WebCoreSupport/FrameLoaderClientQt.cpp:1544
#45 0x00007f6c5d9c899a in WebCore::FrameLoaderClientQt::dispatchDidFinishLoad (this=0x3798750) at ../../Source/WebKit/qt/WebCoreSupport/FrameLoaderClientQt.cpp:514
#46 0x00007f6c5f836cc9 in WebCore::FrameLoader::checkLoadCompleteForThisFrame (this=0x7f6c509efb18) at ../../Source/WebCore/loader/FrameLoader.cpp:2295
#47 0x00007f6c5f82c08e in WebCore::FrameLoader::checkLoadComplete (this=0x7f6c509efb18) at ../../Source/WebCore/loader/FrameLoader.cpp:2482
#48 0x00007f6c5f82ba42 in WebCore::FrameLoader::checkCompleted (this=0x7f6c509efb18) at ../../Source/WebCore/loader/FrameLoader.cpp:809
#49 0x00007f6c5f82ba95 in WebCore::FrameLoader::loadDone (this=0x7f6c509efb18) at ../../Source/WebCore/loader/FrameLoader.cpp:736
#50 0x00007f6c5f8c00bd in WebCore::CachedResourceLoader::loadDone (this=0x7f6c50964400, resource=0x7f6bfd7db380, shouldPerformPostLoadActions=true) at ../../Source/WebCore/loader/cache/CachedResourceLoader.cpp:971
#51 0x00007f6c5f881d3c in WebCore::SubresourceLoader::notifyDone (this=0x7f6c50908500) at ../../Source/WebCore/loader/SubresourceLoader.cpp:509
#52 0x00007f6c5f881882 in WebCore::SubresourceLoader::didFinishLoading (this=0x7f6c50908500, finishTime=0) at ../../Source/WebCore/loader/SubresourceLoader.cpp:435
#53 0x00007f6c5f87ac05 in WebCore::ResourceLoader::didFinishLoading (this=0x7f6c50908500, finishTime=0) at ../../Source/WebCore/loader/ResourceLoader.cpp:643
#54 0x00007f6c5fcd210f in WebCore::QNetworkReplyHandler::finish (this=0x37ee3d0) at ../../Source/WebCore/platform/network/qt/QNetworkReplyHandler.cpp:521
#55 0x00007f6c5fcd025c in WebCore::QNetworkReplyHandlerCallQueue::flush (this=0x37ee408) at ../../Source/WebCore/platform/network/qt/QNetworkReplyHandler.cpp:255
#56 0x00007f6c5fcd0177 in WebCore::QNetworkReplyHandlerCallQueue::push (this=0x37ee408, method=(void (WebCore::QNetworkReplyHandler::*)(WebCore::QNetworkReplyHandler * const)) 0x7f6c5fcd1ef0 <WebCore::QNetworkReplyHandler::finish()>) at ../../Source/WebCore/platform/network/qt/QNetworkReplyHandler.cpp:215
#57 0x00007f6c5fcd288d in WebCore::QNetworkReplyWrapper::didReceiveFinished (this=0x38ab1b0) at ../../Source/WebCore/platform/network/qt/QNetworkReplyHandler.cpp:414
#58 0x00007f6c5fcd4cdd in WebCore::QNetworkReplyWrapper::qt_static_metacall (_o=0x38ab1b0, _c=QMetaObject::InvokeMetaMethod, _id=1, _a=0x7ffeb03ffa40) at Source/WebCore/moc_QNetworkReplyHandler.cpp:177
#59 0x00007f6c586fd2c1 in QMetaObject::activate(QObject*, int, int, void**) () from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/DependenciesQT/Root/lib/libQt5Core.so.5
#60 0x00007f6c58f45985 in ?? () from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/DependenciesQT/Root/lib/libQt5Network.so.5
#61 0x00007f6c586fe0c6 in QObject::event(QEvent*) () from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/DependenciesQT/Root/lib/libQt5Core.so.5
#62 0x00007f6c5ce66fec in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/DependenciesQT/Root/lib/libQt5Widgets.so.5
#63 0x00007f6c5ce6c000 in QApplication::notify(QObject*, QEvent*) () from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/DependenciesQT/Root/lib/libQt5Widgets.so.5
#64 0x00007f6c586cda25 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/DependenciesQT/Root/lib/libQt5Core.so.5
#65 0x00007f6c586cf8bf in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/DependenciesQT/Root/lib/libQt5Core.so.5
#66 0x00007f6c58725983 in ?? () from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/DependenciesQT/Root/lib/libQt5Core.so.5
#67 0x00007f6c5a874d74 in g_main_dispatch (context=0x7f6c08001710) at gmain.c:3122
#68 g_main_context_dispatch (context=context@entry=0x7f6c08001710) at gmain.c:3737
#69 0x00007f6c5a874fc8 in g_main_context_iterate (context=context@entry=0x7f6c08001710, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3808
#70 0x00007f6c5a87506c in g_main_context_iteration (context=0x7f6c08001710, may_block=1) at gmain.c:3869
#71 0x00007f6c58724dfc in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/DependenciesQT/Root/lib/libQt5Core.so.5
#72 0x00007f6c586cb97b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/DependenciesQT/Root/lib/libQt5Core.so.5
#73 0x00007f6c586d3006 in QCoreApplication::exec() () from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/DependenciesQT/Root/lib/libQt5Core.so.5
#74 0x000000000045df44 in main (argc=2, argv=0x7ffeb04004e8) at ../../Tools/DumpRenderTree/qt/DumpRenderTreeMain.cpp:201
```

**Comment by annulen** [comment]
Same bug in css3/masking/mask-luminance-png.html
