### ISSUE TITLE
webgl/1.0.2/conformance/context/context-release-with-workers.html crashes in release build

### ISSUE THREAD

**Issue by annulen** [annulen/webkit#405]
* Crash does not reproduce when test runs alone, only with other tests
* Backtrace (Qt 5.4.0 as in jhbuild)
```
Thread 1 (Thread 0x7f80933fe700 (LWP 14555)):
#0  0x00007f80f156adae in (anonymous namespace)::Q_QGS_privateDb::innerFunction()::Holder::~Holder() () at text/qfontdatabase.cpp:201
#1  0x00007f80f02dd1a9 in __run_exit_handlers (status=139, listp=0x7f80f065f6c8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true) at exit.c:82
#2  0x00007f80f02dd1f5 in __GI_exit (status=<optimized out>) at exit.c:104
#3  0x0000000000cbb7e2 in dumpBacktraceSignalHandler(int) ()
#4  <signal handler called>
#5  isEmpty (this=0x1d8) at ../../include/QtCore/../../src/corelib/tools/qvector.h:84
#6  QThreadStorageData::finish (p=p@entry=0x1d8) at thread/qthreadstorage.cpp:169
#7  0x00007f80f0f36b9e in QThreadPrivate::finish (arg=arg@entry=0x7f808c0009e0) at thread/qthread_unix.cpp:357
#8  0x00007f80f0f37941 in ~__pthread_cleanup_class (this=<synthetic pointer>, __in_chrg=<optimized out>) at /usr/include/pthread.h:572
#9  QThreadPrivate::start (arg=0x7f808c0009e0) at thread/qthread_unix.cpp:339
#10 0x00007f80f4e7e184 in start_thread (arg=0x7f80933fe700) at pthread_create.c:312
#11 0x00007f80f039b37d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```
* Valgrind [1] shows following error:
```
QThread::wait: Thread tried to wait on itself
QThread: Destroyed while thread is still running
==15752== Thread 9 QThread:
==15752== Invalid read of size 8
==15752==    at 0xC23E2E5: testAndSetRelaxed<QMutexData*> (qatomic_x86.h:259)
==15752==    by 0xC23E2E5: testAndSetAcquire<QMutexData*, QMutexData*> (qgenericatomic.h:166)
==15752==    by 0xC23E2E5: testAndSetAcquire (qbasicatomic.h:270)
==15752==    by 0xC23E2E5: fastTryLock (qmutex.h:82)
==15752==    by 0xC23E2E5: QMutex::lock() (qmutex.cpp:212)
==15752==    by 0xC4699A5: relock (qmutex.h:146)
==15752==    by 0xC4699A5: ~LoopReference (qeventloop.cpp:188)
==15752==    by 0xC4699A5: QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (qeventloop.cpp:196)
==15752==    by 0xC240CE9: QThread::exec() (qthread.cpp:503)
==15752==    by 0xC24591E: QThreadPrivate::start(void*) (qthread_unix.cpp:337)
==15752==    by 0x84D5183: start_thread (pthread_create.c:312)
==15752==    by 0xCFF537C: clone (clone.S:111)
==15752==  Address 0x1180df30 is 112 bytes inside a block of size 168 free'd
==15752==    at 0x4C2C2BC: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==15752==    by 0xC4A3993: cleanup (qscopedpointer.h:54)
==15752==    by 0xC4A3993: ~QScopedPointer (qscopedpointer.h:101)
==15752==    by 0xC4A3993: QObject::~QObject() (qobject.cpp:882)
==15752==    by 0xC23FFBE: QThread::~QThread() (qthread.cpp:406)
==15752==    by 0xC2400A8: QThread::~QThread() (qthread.cpp:421)
==15752==    by 0xCC9F92: WTF::WorkQueue::~WorkQueue() (in /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/Release/bin/DumpRenderTree)
==15752==    by 0xCF470C: WTF::WorkQueue::WorkItemQt::~WorkItemQt() (in /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/Release/bin/DumpRenderTree)
==15752==    by 0xC49BEBB: QObject::event(QEvent*) (qobject.cpp:1226)
==15752==    by 0x7960FEB: QApplicationPrivate::notify_helper(QObject*, QEvent*) (qapplication.cpp:3722)
==15752==    by 0x7965FFF: QApplication::notify(QObject*, QEvent*) (qapplication.cpp:3505)
==15752==    by 0xC46BA24: QCoreApplication::notifyInternal(QObject*, QEvent*) (qcoreapplication.cpp:932)
==15752==    by 0xC4C280C: sendEvent (qcoreapplication.h:228)
==15752==    by 0xC4C280C: QTimerInfoList::activateTimers() (qtimerinfo_unix.cpp:635)
==15752==    by 0xC4C2B30: timerSourceDispatch(_GSource*, int (*)(void*), void*) (qeventdispatcher_glib.cpp:177)
...
...
...
==15752== Invalid read of size 8
==15752==    at 0xC244B3F: data (qscopedpointer.h:135)
==15752==    by 0xC244B3F: qGetPtrHelper<QScopedPointer<QObjectData> > (qglobal.h:961)
==15752==    by 0xC244B3F: d_func (qthread.h:129)
==15752==    by 0xC244B3F: QThreadPrivate::finish(void*) (qthread_unix.cpp:347)
==15752==    by 0xC245940: ~__pthread_cleanup_class (pthread.h:572)
==15752==    by 0xC245940: QThreadPrivate::start(void*) (qthread_unix.cpp:339)
==15752==    by 0x84D5183: start_thread (pthread_create.c:312)
==15752==    by 0xCFF537C: clone (clone.S:111)
==15752==  Address 0x1340ca68 is 8 bytes inside a block of size 16 free'd
==15752==    at 0x4C2C2BC: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==15752==    by 0xCC9F92: WTF::WorkQueue::~WorkQueue() (in /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/Release/bin/DumpRenderTree)
==15752==    by 0xCF470C: WTF::WorkQueue::WorkItemQt::~WorkItemQt() (in /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/Release/bin/DumpRenderTree)
==15752==    by 0xC49BEBB: QObject::event(QEvent*) (qobject.cpp:1226)
==15752==    by 0x7960FEB: QApplicationPrivate::notify_helper(QObject*, QEvent*) (qapplication.cpp:3722)
==15752==    by 0x7965FFF: QApplication::notify(QObject*, QEvent*) (qapplication.cpp:3505)
==15752==    by 0xC46BA24: QCoreApplication::notifyInternal(QObject*, QEvent*) (qcoreapplication.cpp:932)
==15752==    by 0xC4C280C: sendEvent (qcoreapplication.h:228)
==15752==    by 0xC4C280C: QTimerInfoList::activateTimers() (qtimerinfo_unix.cpp:635)
==15752==    by 0xC4C2B30: timerSourceDispatch(_GSource*, int (*)(void*), void*) (qeventdispatcher_glib.cpp:177)
==15752==    by 0xB612D73: g_main_dispatch (gmain.c:3122)
==15752==    by 0xB612D73: g_main_context_dispatch (gmain.c:3737)
==15752==    by 0xB612FC7: g_main_context_iterate.isra.24 (gmain.c:3808)
==15752==    by 0xB61306B: g_main_context_iteration (gmain.c:3869)

```

[1] valgrind --leak-check=no --smc-check=all --track-origins=yes WebKitBuild/Release/bin/DumpRenderTree -p -v LayoutTests/webgl/1.0.2/conformance/context/context-release-with-workers.html

**Comment by annulen** [comment]
* Valgrind results are probably meaningless because it is single threaded (`QThread::wait: Thread tried to wait on itself` - this meassage didn't occur without valgrind)
* No new info when using Release + `-g` build
* TODO: try #333
