### ISSUE TITLE
ASSERTION FAILED: isMainThread() when loggin in to Twitter

### ISSUE THREAD

**Issue by annulen** [annulen/webkit#437]
See https://trac.webkit.org/changeset/211372 for SOUP fix
```
#0  WTFCrash () at ../../Source/WTF/wtf/Assertions.cpp:322
#1  0x00007ffff3bd2cf9 in WebCore::builtinResourceHandleConstructorMap () at ../../Source/WebCore/platform/network/ResourceHandle.cpp:50
#2  0x00007ffff3bd3130 in WebCore::ResourceHandle::create (context=0x0, request=..., client=0x7fff49594000, defersLoading=true, 
    shouldContentSniff=false) at ../../Source/WebCore/platform/network/ResourceHandle.cpp:90
#3  0x00007ffff3dc8edf in ResourceHandleStreamingClient::ResourceHandleStreamingClient(_WebKitWebSrc*, WebCore::ResourceRequest&&)::$_3::operator()() const (this=0x7fff440e9af0) at ../../Source/WebCore/platform/graphics/gstreamer/WebKitWebSourceGStreamer.cpp:1076
#4  0x00007ffff3dc8c7d in std::_Function_handler<void (), ResourceHandleStreamingClient::ResourceHandleStreamingClient(_WebKitWebSrc*, WebCore::ResourceRequest&&)::$_3>::_M_invoke(std::_Any_data const&) (__functor=...)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.0/../../../../include/c++/6.2.0/functional:1740
#5  0x00007ffff198e94e in std::function<void ()>::operator()() const (this=0x7fff435f8e48)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.0/../../../../include/c++/6.2.0/functional:2136
#6  0x00007ffff29c0d3e in WTF::threadEntryPoint (contextData=0x7fff8ad02500) at ../../Source/WTF/wtf/Threading.cpp:58
#7  0x00007ffff29fdc57 in WTF::wtfThreadEntryPoint (param=0x7fff49596010) at ../../Source/WTF/wtf/ThreadingPthreads.cpp:164
#8  0x00007fffef6e7184 in start_thread (arg=0x7fff435f9700) at pthread_create.c:312
#9  0x00007ffff034237d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by annulen** [comment]
Duplicate of #487
