### ISSUE TITLE
Segfault on QOpenGLWidget

### ISSUE THREAD

**Issue by herbmillerjr** [annulen/webkit#451]
http://vitorteixeira.me/Solar-System-Motion-Simulator/

When running the above URL through QtTestBrowser and Enable WebGL on, enabling QGLWidget or QOpenGLWidget crashes with the following message:

`http://vitorteixeira.me/Solar-System-Motion-Simulator/js/THREE-r72.js:%2" "THREE.WebGLRenderer: Texture is not power of two. Texture.minFilter should be set to THREE.NearestFilter or THREE.LinearFilter. ( textures/jupiter.jpg )"
Segmentation fault (core dumped)`

Graphics chip is Intel Skylake. Doesn't seem to affect my nVidia machine.

**Comment by herbmillerjr** [comment]
Correction. I still get the "power of two" error on nVidia card and nVidia card segfaults on QOpenGLWidget but not QGLWidget.

Intel card segfaults on both.

I'll get you a backtrace in a sec.

**Comment by herbmillerjr** [comment]
backtrace

```#0  0x00007ffff464bbfd in QOpenGLContextPrivate::maxTextureSize() () from /usr/local/lib/libQt5Gui.so.5
#1  0x00007ffff49013ee in QOpenGL2PaintEngineEx::drawImage(QRectF const&, QImage const&, QRectF const&, QFlags<Qt::ImageConversionFlag>) () from /usr/local/lib/libQt5Gui.so.5
#2  0x00007ffff4906983 in QOpenGL2PaintEngineEx::drawPixmap(QRectF const&, QPixmap const&, QRectF const&) () from /usr/local/lib/libQt5Gui.so.5
#3  0x00007ffff484681d in QPainter::drawPixmap(QRectF const&, QPixmap const&, QRectF const&) () from /usr/local/lib/libQt5Gui.so.5
#4  0x00007ffff6b28eb2 in WebCore::StillImage::draw(WebCore::GraphicsContext&, WebCore::FloatRect const&, WebCore::FloatRect const&, WebCore::CompositeOperator, WebCore::BlendMode, WebCore::ImageOrientationDescription) () from /data/src/webkit/lib/libQt5WebKit.so.5
#5  0x00007ffff69cf3b7 in WebCore::GraphicsContext::drawImage(WebCore::Image&, WebCore::FloatRect const&, WebCore::ImagePaintingOptions const&) ()
   from /data/src/webkit/lib/libQt5WebKit.so.5
#6  0x00007ffff63c7c73 in WebCore::HTMLCanvasElement::paint(WebCore::GraphicsContext&, WebCore::LayoutRect const&) () from /data/src/webkit/lib/libQt5WebKit.so.5
#7  0x00007ffff61843f8 in WebCore::RenderHTMLCanvas::paintReplaced(WebCore::PaintInfo&, WebCore::LayoutPoint const&) () from /data/src/webkit/lib/libQt5WebKit.so.5
#8  0x00007ffff6286eff in WebCore::RenderReplaced::paint(WebCore::PaintInfo&, WebCore::LayoutPoint const&) () from /data/src/webkit/lib/libQt5WebKit.so.5
#9  0x00007ffff61d248d in WebCore::RenderLayer::paintForegroundForFragmentsWithPhase(WebCore::PaintPhase, WTF::Vector<WebCore::LayerFragment, 1ul, WTF::CrashOnOverflow, 16ul> const&, WebCore::GraphicsContext&, WebCore::RenderLayer::LayerPaintingInfo const&, unsigned int, WebCore::RenderObject*) () from /data/src/webkit/lib/libQt5WebKit.so.5
#10 0x00007ffff6290924 in WebCore::RenderLayer::paintForegroundForFragments(WTF::Vector<WebCore::LayerFragment, 1ul, WTF::CrashOnOverflow, 16ul> const&, WebCore::GraphicsContext&, WebCore::GraphicsContext&, WebCore::LayoutRect const&, bool, WebCore::RenderLayer::LayerPaintingInfo const&, unsigned int, WebCore::RenderObject*, bool) () from /data/src/webkit/lib/libQt5WebKit.so.5
#11 0x00007ffff62ab346 in WebCore::RenderLayer::paintLayerContents(WebCore::GraphicsContext&, WebCore::RenderLayer::LayerPaintingInfo const&, unsigned int) ()
   from /data/src/webkit/lib/libQt5WebKit.so.5
#12 0x00007ffff62ac198 in WebCore::RenderLayer::paintLayer(WebCore::GraphicsContext&, WebCore::RenderLayer::LayerPaintingInfo const&, unsigned int) ()
   from /data/src/webkit/lib/libQt5WebKit.so.5
#13 0x00007ffff62b48b5 in WebCore::RenderLayer::paintList(WTF::Vector<WebCore::RenderLayer*, 0ul, WTF::CrashOnOverflow, 16ul>*, WebCore::GraphicsContext&, WebCore::RenderLayer::LayerPaintingInfo const&, unsigned int) () from /data/src/webkit/lib/libQt5WebKit.so.5
#14 0x00007ffff62aae12 in WebCore::RenderLayer::paintLayerContents(WebCore::GraphicsContext&, WebCore::RenderLayer::LayerPaintingInfo const&, unsigned int) ()
   from /data/src/webkit/lib/libQt5WebKit.so.5
#15 0x00007ffff62ac198 in WebCore::RenderLayer::paintLayer(WebCore::GraphicsContext&, WebCore::RenderLayer::LayerPaintingInfo const&, unsigned int) ()
   from /data/src/webkit/lib/libQt5WebKit.so.5
#16 0x00007ffff62b48b5 in WebCore::RenderLayer::paintList(WTF::Vector<WebCore::RenderLayer*, 0ul, WTF::CrashOnOverflow, 16ul>*, WebCore::GraphicsContext&, WebCore::RenderLayer::LayerPaintingInfo const&, unsigned int) () from /data/src/webkit/lib/libQt5WebKit.so.5
#17 0x00007ffff62aae2f in WebCore::RenderLayer::paintLayerContents(WebCore::GraphicsContext&, WebCore::RenderLayer::LayerPaintingInfo const&, unsigned int) ()
   from /data/src/webkit/lib/libQt5WebKit.so.5
#18 0x00007ffff62ac198 in WebCore::RenderLayer::paintLayer(WebCore::GraphicsContext&, WebCore::RenderLayer::LayerPaintingInfo const&, unsigned int) ()
   from /data/src/webkit/lib/libQt5WebKit.so.5
#19 0x00007ffff62ac2bd in WebCore::RenderLayer::paint(WebCore::GraphicsContext&, WebCore::LayoutRect const&, WebCore::LayoutSize const&, unsigned int, WebCore::RenderObject*, unsigned int)
    () from /data/src/webkit/lib/libQt5WebKit.so.5
#20 0x00007ffff68d11a1 in WebCore::FrameView::paintContents(WebCore::GraphicsContext&, WebCore::IntRect const&) () from /data/src/webkit/lib/libQt5WebKit.so.5
#21 0x00007ffff57b7d0f in QWebFrameAdapter::renderRelativeCoords(QPainter*, int, QRegion const&) () from /data/src/webkit/lib/libQt5WebKit.so.5
#22 0x00007ffff7fce62e in QWebFrame::render(QPainter*, QFlags<QWebFrame::RenderLayer>, QRegion const&) () from /data/src/webkit/lib/libQt5WebKitWidgets.so.5
#23 0x00007ffff7fcbf9a in QGraphicsWebView::paint(QPainter*, QStyleOptionGraphicsItem const*, QWidget*) () from /data/src/webkit/lib/libQt5WebKitWidgets.so.5
#24 0x00007ffff4ec9195 in ?? () from /usr/local/lib/libQt5Widgets.so.5
#25 0x00007ffff4ed91f2 in ?? () from /usr/local/lib/libQt5Widgets.so.5
#26 0x00007ffff4edb4b4 in ?? () from /usr/local/lib/libQt5Widgets.so.5
#27 0x00007ffff4edc07e in ?? () from /usr/local/lib/libQt5Widgets.so.5
#28 0x00007ffff4edc73a in ?? () from /usr/local/lib/libQt5Widgets.so.5
#29 0x00007ffff4efe0da in QGraphicsView::paintEvent(QPaintEvent*) () from /usr/local/lib/libQt5Widgets.so.5
#30 0x00007ffff4c10ff8 in QWidget::event(QEvent*) () from /usr/local/lib/libQt5Widgets.so.5
#31 0x00007ffff4cf7b3e in QFrame::event(QEvent*) () from /usr/local/lib/libQt5Widgets.so.5
#32 0x00007ffff4efcbbb in QGraphicsView::viewportEvent(QEvent*) () from /usr/local/lib/libQt5Widgets.so.5
#33 0x00007ffff428e072 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /usr/local/lib/libQt5Core.so.5
#34 0x00007ffff4bc9cd5 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/local/lib/libQt5Widgets.so.5
#35 0x00007ffff4bd1716 in QApplication::notify(QObject*, QEvent*) () from /usr/local/lib/libQt5Widgets.so.5
#36 0x00007ffff428e308 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/local/lib/libQt5Core.so.5```

**Comment by annulen** [comment]
What Qt version is it? Also it would be better to get backtrace with debug info in Qt, to see line numbers in Qt functions

**Comment by herbmillerjr** [comment]
Qt 5.8. I'll get you a better backtrace soon as I'm in front of the machine that has the debug version built.

**Comment by herbmillerjr** [comment]
```
#0  0x00007ffff005e637 in QOpenGLFunctions_1_0::glGetTexLevelParameteriv (this=0x485a260, target=32868, level=0, pname=4096, params=0x7fffffff8c80) at ../../include/QtGui/../../src/gui/opengl/qopenglfunctions_1_0.h:408
#1  0x00007ffff005b215 in QOpenGLContextPrivate::maxTextureSize (this=0x33b4040) at kernel/qopenglcontext.cpp:387
#2  0x00007ffff036bad4 in QOpenGL2PaintEngineEx::drawImage (this=0x394dbe0, dest=..., image=..., src=...) at opengl/qopenglpaintengine.cpp:1469
#3  0x00007ffff036b6b1 in QOpenGL2PaintEngineEx::drawPixmap (this=0x394dbe0, dest=..., pixmap=..., src=...) at opengl/qopenglpaintengine.cpp:1435
#4  0x00007ffff027ad85 in QPainter::drawPixmap (this=0x7fffffffb120, r=..., pm=..., sr=...) at painting/qpainter.cpp:5198
#5  0x00007ffff37272fe in (anonymous namespace)::StillImage::draw (this=0x7fff49547330, ctxt=..., dst=..., src=..., op=(anonymous namespace)::CompositeSourceOver, blendMode=(anonymous namespace)::BlendModeNormal)
    at /home/hmiller/src/qt/webkit/Source/WebCore/platform/graphics/qt/StillImageQt.cpp:100
#6  0x00007ffff356dcbc in (anonymous namespace)::GraphicsContext::drawImage (this=0x7fffffffa5d0, image=..., destination=..., source=..., imagePaintingOptions=...)
    at /home/hmiller/src/qt/webkit/Source/WebCore/platform/graphics/GraphicsContext.cpp:747
#7  0x00007ffff400b60b in (anonymous namespace)::ImageBufferDataPrivateUnaccelerated::draw (this=0xa8ecf0, destContext=..., destRect=..., srcRect=..., op=(anonymous namespace)::CompositeSourceOver, 
    blendMode=(anonymous namespace)::BlendModeNormal, ownContext=false) at /home/hmiller/src/qt/webkit/Source/WebCore/platform/graphics/qt/ImageBufferDataQt.cpp:419
#8  0x00007ffff371ab4d in (anonymous namespace)::ImageBuffer::draw (this=0x7fff49547300, destContext=..., destRect=..., srcRect=..., op=(anonymous namespace)::CompositeSourceOver, blendMode=(anonymous namespace)::BlendModeNormal)
    at /home/hmiller/src/qt/webkit/Source/WebCore/platform/graphics/qt/ImageBufferQt.cpp:127
#9  0x00007ffff356e172 in (anonymous namespace)::GraphicsContext::drawImageBuffer (this=0x7fffffffa5d0, image=..., destination=..., source=..., imagePaintingOptions=...)
    at /home/hmiller/src/qt/webkit/Source/WebCore/platform/graphics/GraphicsContext.cpp:801
#10 0x00007ffff356e0d9 in (anonymous namespace)::GraphicsContext::drawImageBuffer (this=0x7fffffffa5d0, image=..., destination=..., imagePaintingOptions=...)
    at /home/hmiller/src/qt/webkit/Source/WebCore/platform/graphics/GraphicsContext.cpp:792
#11 0x00007ffff2a895fa in (anonymous namespace)::HTMLCanvasElement::paint (this=0x7fff7e4fcd80, context=..., r=...) at /home/hmiller/src/qt/webkit/Source/WebCore/html/HTMLCanvasElement.cpp:438
#12 0x00007ffff26f927d in (anonymous namespace)::RenderHTMLCanvas::paintReplaced (this=0x7fff7c15b098, paintInfo=..., paintOffset=...) at /home/hmiller/src/qt/webkit/Source/WebCore/rendering/RenderHTMLCanvas.cpp:89
#13 0x00007ffff276ff54 in (anonymous namespace)::RenderReplaced::paint (this=0x7fff7c15b098, paintInfo=..., paintOffset=...) at /home/hmiller/src/qt/webkit/Source/WebCore/rendering/RenderReplaced.cpp:189
#14 0x00007ffff2719c95 in (anonymous namespace)::RenderLayer::paintForegroundForFragmentsWithPhase (this=0x7fff495dda20, phase=(anonymous namespace)::PaintPhaseForeground, layerFragments=..., context=..., localPaintingInfo=..., 
    paintBehavior=0, subtreePaintRootForRenderer=0x0) at /home/hmiller/src/qt/webkit/Source/WebCore/rendering/RenderLayer.cpp:4737
#15 0x00007ffff271999b in (anonymous namespace)::RenderLayer::paintForegroundForFragments (this=0x7fff495dda20, layerFragments=..., context=..., transparencyLayerContext=..., transparencyPaintDirtyRect=..., haveTransparency=false, 
    localPaintingInfo=..., paintBehavior=0, subtreePaintRootForRenderer=0x0, selectionOnly=false) at /home/hmiller/src/qt/webkit/Source/WebCore/rendering/RenderLayer.cpp:4714
#16 0x00007ffff2717b32 in (anonymous namespace)::RenderLayer::paintLayerContents (this=0x7fff495dda20, originalContext=..., paintingInfo=..., paintFlags=96) at /home/hmiller/src/qt/webkit/Source/WebCore/rendering/RenderLayer.cpp:4342
#17 0x00007ffff27162df in (anonymous namespace)::RenderLayer::paintLayerContentsAndReflection (this=0x7fff495dda20, context=..., paintingInfo=..., paintFlags=96) at /home/hmiller/src/qt/webkit/Source/WebCore/rendering/RenderLayer.cpp:3998
#18 0x00007ffff2716197 in (anonymous namespace)::RenderLayer::paintLayer (this=0x7fff495dda20, context=..., paintingInfo=..., paintFlags=96) at /home/hmiller/src/qt/webkit/Source/WebCore/rendering/RenderLayer.cpp:3980
#19 0x00007ffff27183fb in (anonymous namespace)::RenderLayer::paintList (this=0x7fff495ddea0, list=0x7fff7c0a8f10, context=..., paintingInfo=..., paintFlags=96) at /home/hmiller/src/qt/webkit/Source/WebCore/rendering/RenderLayer.cpp:4448
#20 0x00007ffff2717bc4 in (anonymous namespace)::RenderLayer::paintLayerContents (this=0x7fff495ddea0, originalContext=..., paintingInfo=..., paintFlags=96) at /home/hmiller/src/qt/webkit/Source/WebCore/rendering/RenderLayer.cpp:4350
#21 0x00007ffff27162df in (anonymous namespace)::RenderLayer::paintLayerContentsAndReflection (this=0x7fff495ddea0, context=..., paintingInfo=..., paintFlags=96) at /home/hmiller/src/qt/webkit/Source/WebCore/rendering/RenderLayer.cpp:3998
#22 0x00007ffff2716197 in (anonymous namespace)::RenderLayer::paintLayer (this=0x7fff495ddea0, context=..., paintingInfo=..., paintFlags=96) at /home/hmiller/src/qt/webkit/Source/WebCore/rendering/RenderLayer.cpp:3980
#23 0x00007ffff27183fb in (anonymous namespace)::RenderLayer::paintList (this=0x7fff7e521360, list=0x7fff7c0a8ef0, context=..., paintingInfo=..., paintFlags=96) at /home/hmiller/src/qt/webkit/Source/WebCore/rendering/RenderLayer.cpp:4448
#24 0x00007ffff2717bff in (anonymous namespace)::RenderLayer::paintLayerContents (this=0x7fff7e521360, originalContext=..., paintingInfo=..., paintFlags=96) at /home/hmiller/src/qt/webkit/Source/WebCore/rendering/RenderLayer.cpp:4353
#25 0x00007ffff27162df in (anonymous namespace)::RenderLayer::paintLayerContentsAndReflection (this=0x7fff7e521360, context=..., paintingInfo=..., paintFlags=0) at /home/hmiller/src/qt/webkit/Source/WebCore/rendering/RenderLayer.cpp:3998
#26 0x00007ffff2716197 in (anonymous namespace)::RenderLayer::paintLayer (this=0x7fff7e521360, context=..., paintingInfo=..., paintFlags=0) at /home/hmiller/src/qt/webkit/Source/WebCore/rendering/RenderLayer.cpp:3980
#27 0x00007ffff2715031 in (anonymous namespace)::RenderLayer::paint (this=0x7fff7e521360, context=..., damageRect=..., subpixelAccumulation=..., paintBehavior=0, subtreePaintRoot=0x0, paintFlags=0)
    at /home/hmiller/src/qt/webkit/Source/WebCore/rendering/RenderLayer.cpp:3784
#28 0x00007ffff341eba6 in (anonymous namespace)::FrameView::paintContents (this=0x7fffe0307200, context=..., dirtyRect=...) at /home/hmiller/src/qt/webkit/Source/WebCore/page/FrameView.cpp:4092
#29 0x00007ffff1839675 in QWebFrameAdapter::renderRelativeCoords (this=0x955310, painter=0x7fffffffb120, layers=255, clip=...) at /home/hmiller/src/qt/webkit/Source/WebKit/qt/WebCoreSupport/QWebFrameAdapter.cpp:530
#30 0x00007ffff7fb9ba6 in QWebFrame::render (this=0x9888e0, painter=0x7fffffffb120, layer=..., clip=...) at /home/hmiller/src/qt/webkit/Source/WebKit/qt/WidgetApi/qwebframe.cpp:631
#31 0x00007ffff7fb4910 in QGraphicsWebView::paint (this=0x9fb010, painter=0x7fffffffb120, option=0x54a478) at /home/hmiller/src/qt/webkit/Source/WebKit/qt/WidgetApi/qgraphicswebview.cpp:254
#32 0x00007ffff0b06c47 in _q_paintItem (item=0x9fb020, painter=0x7fffffffb120, option=0x54a478, widget=0xb22090, useWindowOpacity=true, painterStateProtection=true) at graphicsview/qgraphicsscene.cpp:4310
#33 0x00007ffff0b07337 in QGraphicsScenePrivate::drawItemHelper (this=0x54a260, item=0x9fb020, painter=0x7fffffffb120, option=0x54a478, widget=0xb22090, painterStateProtection=true) at graphicsview/qgraphicsscene.cpp:4406
#34 0x00007ffff0b0a7ef in QGraphicsScenePrivate::draw (this=0x54a260, item=0x9fb020, painter=0x7fffffffb120, viewTransform=0x0, transformPtr=0x94dda0, exposedRegion=0xb3a7e0, widget=0xb22090, opacity=1, effectTransform=0x0, 
    wasDirtyParentSceneTransform=false, drawItem=true) at graphicsview/qgraphicsscene.cpp:4962
#35 0x00007ffff0b09f75 in QGraphicsScenePrivate::drawSubtreeRecursive (this=0x54a260, item=0x9fb020, painter=0x7fffffffb120, viewTransform=0x0, exposedRegion=0xb3a7e0, widget=0xb22090, parentOpacity=1, effectTransform=0x0)
    at graphicsview/qgraphicsscene.cpp:4853
#36 0x00007ffff0b091e0 in QGraphicsScenePrivate::drawItems (this=0x54a260, painter=0x7fffffffb120, viewTransform=0x0, exposedRegion=0xb3a7e0, widget=0xb22090) at graphicsview/qgraphicsscene.cpp:4714
#37 0x00007ffff0b419a8 in QGraphicsView::paintEvent (this=0x5aab40, event=0x7fffffffba90) at graphicsview/qgraphicsview.cpp:3545
#38 0x0000000000431f2f in WebViewGraphicsBased::paintEvent (this=0x5aab40, event=0x7fffffffba90) at /home/hmiller/src/qt/webkit/Tools/QtTestBrowser/webview.cpp:242
#39 0x00007ffff07292e6 in QWidget::event (this=0x5aab40, event=0x7fffffffba90) at kernel/qwidget.cpp:8932
#40 0x00007ffff08773ef in QFrame::event (this=0x5aab40, e=0x7fffffffba90) at widgets/qframe.cpp:550
#41 0x00007ffff09315c2 in QAbstractScrollArea::viewportEvent (this=0x5aab40, e=0x7fffffffba90) at widgets/qabstractscrollarea.cpp:1207
#42 0x00007ffff0b3f19e in QGraphicsView::viewportEvent (this=0x5aab40, event=0x7fffffffba90) at graphicsview/qgraphicsview.cpp:2968
#43 0x00007ffff0932903 in QAbstractScrollAreaPrivate::viewportEvent (this=0xb3a310, event=0x7fffffffba90) at widgets/qabstractscrollarea_p.h:112
#44 0x00007ffff09329ee in QAbstractScrollAreaFilter::eventFilter (this=0x5a5990, o=0xb22090, e=0x7fffffffba90) at widgets/qabstractscrollarea_p.h:128
#45 0x00007fffefb85927 in QCoreApplicationPrivate::sendThroughObjectEventFilters (receiver=0xb22090, event=0x7fffffffba90) at kernel/qcoreapplication.cpp:1099
#46 0x00007ffff06d1f8d in QApplicationPrivate::notify_helper (this=0x46de00, receiver=0xb22090, e=0x7fffffffba90) at kernel/qapplication.cpp:3741
#47 0x00007ffff06d1dba in QApplication::notify (this=0x7fffffffdcf0, receiver=0xb22090, e=0x7fffffffba90) at kernel/qapplication.cpp:3708
#48 0x00007fffefb8552f in QCoreApplication::notifyInternal2 (receiver=0xb22090, event=0x7fffffffba90) at kernel/qcoreapplication.cpp:988
#49 0x00007ffff06d4de8 in QCoreApplication::sendSpontaneousEvent (receiver=0xb22090, event=0x7fffffffba90) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:234
#50 0x00007ffff071ffcb in QWidgetPrivate::sendPaintEvent (this=0xb1e8b0, toBePainted=...) at kernel/qwidget.cpp:5704
#51 0x00007ffff071fab5 in QWidgetPrivate::drawWidget (this=0xb1e8b0, pdev=0x6eb7c0, rgn=..., offset=..., flags=4, sharedPainter=0x0, backingStore=0x52b550) at kernel/qwidget.cpp:5644
#52 0x00007ffff0720975 in QWidgetPrivate::paintSiblingsRecursive (this=0xb3a310, pdev=0x6eb7c0, siblings=..., index=3, rgn=..., offset=..., flags=4, sharedPainter=0x0, backingStore=0x52b550) at kernel/qwidget.cpp:5839
#53 0x00007ffff071ff45 in QWidgetPrivate::drawWidget (this=0xb3a310, pdev=0x6eb7c0, rgn=..., offset=..., flags=4, sharedPainter=0x0, backingStore=0x52b550) at kernel/qwidget.cpp:5696
#54 0x00007ffff0720975 in QWidgetPrivate::paintSiblingsRecursive (this=0x5a6900, pdev=0x6eb7c0, siblings=..., index=0, rgn=..., offset=..., flags=4, sharedPainter=0x0, backingStore=0x52b550) at kernel/qwidget.cpp:5839
#55 0x00007ffff071ff45 in QWidgetPrivate::drawWidget (this=0x5a6900, pdev=0x6eb7c0, rgn=..., offset=..., flags=4, sharedPainter=0x0, backingStore=0x52b550) at kernel/qwidget.cpp:5696
#56 0x00007ffff0720975 in QWidgetPrivate::paintSiblingsRecursive (this=0x54eeb0, pdev=0x6eb7c0, siblings=..., index=0, rgn=..., offset=..., flags=4, sharedPainter=0x0, backingStore=0x52b550) at kernel/qwidget.cpp:5839
#57 0x00007ffff0720836 in QWidgetPrivate::paintSiblingsRecursive (this=0x54eeb0, pdev=0x6eb7c0, siblings=..., index=1, rgn=..., offset=..., flags=4, sharedPainter=0x0, backingStore=0x52b550) at kernel/qwidget.cpp:5826
#58 0x00007ffff0720836 in QWidgetPrivate::paintSiblingsRecursive (this=0x54eeb0, pdev=0x6eb7c0, siblings=..., index=5, rgn=..., offset=..., flags=4, sharedPainter=0x0, backingStore=0x52b550) at kernel/qwidget.cpp:5826
#59 0x00007ffff071ff45 in QWidgetPrivate::drawWidget (this=0x54eeb0, pdev=0x6eb7c0, rgn=..., offset=..., flags=5, sharedPainter=0x0, backingStore=0x52b550) at kernel/qwidget.cpp:5696
#60 0x00007ffff06e3aff in QWidgetBackingStore::doSync (this=0x52b550) at kernel/qwidgetbackingstore.cpp:1389
#61 0x00007ffff06e26fd in QWidgetBackingStore::sync (this=0x52b550) at kernel/qwidgetbackingstore.cpp:1170
#62 0x00007ffff0715a5a in QWidgetPrivate::syncBackingStore (this=0x54eeb0) at kernel/qwidget.cpp:1962
#63 0x00007ffff0729aaa in QWidget::event (this=0x5822c0, event=0x9c68d0) at kernel/qwidget.cpp:9095
#64 0x00007ffff0898a71 in QMainWindow::event (this=0x5822c0, event=0x9c68d0) at widgets/qmainwindow.cpp:1557
#65 0x00007ffff06d1fb6 in QApplicationPrivate::notify_helper (this=0x46de00, receiver=0x5822c0, e=0x9c68d0) at kernel/qapplication.cpp:3745
#66 0x00007ffff06d1dba in QApplication::notify (this=0x7fffffffdcf0, receiver=0x5822c0, e=0x9c68d0) at kernel/qapplication.cpp:3708
#67 0x00007fffefb8552f in QCoreApplication::notifyInternal2 (receiver=0x5822c0, event=0x9c68d0) at kernel/qcoreapplication.cpp:988
#68 0x00007fffefb898c6 in QCoreApplication::sendEvent (receiver=0x5822c0, event=0x9c68d0) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:231
#69 0x00007fffefb86a82 in QCoreApplicationPrivate::sendPostedEvents (receiver=0x5822c0, event_type=77, data=0x46df70) at kernel/qcoreapplication.cpp:1648
#70 0x00007fffefb863d8 in QCoreApplication::sendPostedEvents (receiver=0x5822c0, event_type=77) at kernel/qcoreapplication.cpp:1502
#71 0x00007ffff0b13107 in QGraphicsViewPrivate::dispatchPendingUpdateRequests (this=0xb3a310) at ../../include/QtWidgets/5.8.0/QtWidgets/private/../../../../../src/widgets/graphicsview/qgraphicsview_p.h:203
#72 0x00007ffff0afa7bb in QGraphicsScenePrivate::_q_processDirtyItems (this=0x54a260) at graphicsview/qgraphicsscene.cpp:508
#73 0x00007ffff0b12419 in QGraphicsScene::qt_static_metacall (_o=0x5a5640, _c=QMetaObject::InvokeMetaMethod, _id=15, _a=0xa8eb50) at .moc/moc_qgraphicsscene.cpp:184
#74 0x00007fffefbc30e5 in QMetaCallEvent::placeMetaCall (this=0xb353f0, object=0x5a5640) at kernel/qobject.cpp:502
#75 0x00007fffefbc42af in QObject::event (this=0x5a5640, e=0xb353f0) at kernel/qobject.cpp:1263
#76 0x00007ffff0b04863 in QGraphicsScene::event (this=0x5a5640, event=0xb353f0) at graphicsview/qgraphicsscene.cpp:3523
#77 0x00007ffff06d1fb6 in QApplicationPrivate::notify_helper (this=0x46de00, receiver=0x5a5640, e=0xb353f0) at kernel/qapplication.cpp:3745
#78 0x00007ffff06cf21e in QApplication::notify (this=0x7fffffffdcf0, receiver=0x5a5640, e=0xb353f0) at kernel/qapplication.cpp:3105
#79 0x00007fffefb8552f in QCoreApplication::notifyInternal2 (receiver=0x5a5640, event=0xb353f0) at kernel/qcoreapplication.cpp:988
#80 0x00007fffefb898c6 in QCoreApplication::sendEvent (receiver=0x5a5640, event=0xb353f0) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:231
#81 0x00007fffefb86a82 in QCoreApplicationPrivate::sendPostedEvents (receiver=0x0, event_type=0, data=0x46df70) at kernel/qcoreapplication.cpp:1648
#82 0x00007fffefb863d8 in QCoreApplication::sendPostedEvents (receiver=0x0, event_type=0) at kernel/qcoreapplication.cpp:1502
#83 0x00007fffefc0c5ff in postEventSourceDispatch (s=0x4a6530) at kernel/qeventdispatcher_glib.cpp:276
#84 0x00007fffeaeb0197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#85 0x00007fffeaeb03f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#86 0x00007fffeaeb049c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#87 0x00007fffefc0ce0a in QEventDispatcherGlib::processEvents (this=0x4a6640, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#88 0x00007fffe48e5cd8 in QPAEventDispatcherGlib::processEvents (this=0x4a6640, flags=...) at qeventdispatcher_glib.cpp:121
#89 0x00007fffefb81b8e in QEventLoop::processEvents (this=0x7fffffffdb90, flags=...) at kernel/qeventloop.cpp:134
#90 0x00007fffefb81ec5 in QEventLoop::exec (this=0x7fffffffdb90, flags=...) at kernel/qeventloop.cpp:212
#91 0x00007fffefb85d25 in QCoreApplication::exec () at kernel/qcoreapplication.cpp:1261
#92 0x00007fffefffe4e4 in QGuiApplication::exec () at kernel/qguiapplication.cpp:1657
#93 0x00007ffff06cebc5 in QApplication::exec () at kernel/qapplication.cpp:2921
#94 0x00000000004299e1 in launcherMain (app=...) at /home/hmiller/src/qt/webkit/Tools/QtTestBrowser/qttestbrowser.cpp:54
#95 0x000000000042bc35 in main (argc=2, argv=0x7fffffffded8) at /home/hmiller/src/qt/webkit/Tools/QtTestBrowser/qttestbrowser.cpp:336
```

I believe this is what you're looking for?

**Comment by annulen** [comment]
Yep, thanks. It's probably Qt bug indeed, but it needs to be investigated to be reported properly.

Out of curiosity, does it crash if you enable accelerated 2d canvas?

**Comment by herbmillerjr** [comment]
With or without Accelerated 2d Canvas, it only crashed once I enable QOpenGLWidget. However, with Accelerated 2d Canvas and without QOpenGLWidget, it only draws the first few frames and stops, but no crash.
