### ISSUE TITLE
TP5: build failure with qt-5.9 - dynamic_cast not permitted with -fno-rtti

### ISSUE THREAD

**Issue by tjelbert** [annulen/webkit#464]
FAILED: Source/WebCore/CMakeFiles/WebCore.dir/platform/graphics/texmap/GraphicsLayerTextureMapper.cpp.o
/var/lib/sorcery/build/c++     
@Source/WebCore/CMakeFiles/WebCore.dir/platform/graphics/texmap/GraphicsLayerTextureMapper.cpp.o.rsp -MD -MT 
Source/WebCore/CMakeFiles/WebCore.dir/platform/graphics/texmap/GraphicsLayerTextureMapper.cpp.o -MF 
Source/WebCore/CMakeFiles/WebCore.dir/platform/graphics/texmap/GraphicsLayerTextureMapper.cpp.o.d -o 
Source/WebCore/CMakeFiles/WebCore.dir/platform/graphics/texmap/GraphicsLayerTextureMapper.cpp.o -c 
/usr/src/qtwebkit-tp5/Source/WebCore/platform/graphics/texmap/GraphicsLayerTextureMapper.cpp
In file included from ../Source/WTF/wtf/StdLibExtras.h:32:0,
                 from ../Source/WTF/wtf/FastMalloc.h:26,
                 from ../Source/WebCore/config.h:75,
                 from /usr/src/qtwebkit-tp5/Source/WebCore/platform/graphics/texmap/GraphicsLayerTextureMapper.cpp:20:
/usr/src/qtwebkit-tp5/Source/WebCore/platform/graphics/texmap/GraphicsLayerTextureMapper.cpp: In member function 'void 
WebCore::GraphicsLayerTextureMapper::updateBackingStoreIfNeeded()':
/usr/src/qtwebkit-tp5/Source/WebCore/platform/graphics/texmap/GraphicsLayerTextureMapper.cpp:549:78: error: 'dynamic_cast' 
not permitted with -fno-rtti
     ASSERT(dynamic_cast<TextureMapperTiledBackingStore*>(m_backingStore.get()));
                                                                              ^
../Source/WTF/wtf/Assertions.h:250:11: note: in definition of macro 'ASSERT'
     if (!(assertion)) { \
           ^~~~~~~~~

After deleting the ASSERT line, it compiles, but I get a segfault

Thread 1 "otter-browser" received signal SIGSEGV, Segmentation fault.
0x00007ffff1811bee in JSC::DateInstance::calculateGregorianDateTimeUTC(JSC::ExecState*) const ()
   from /opt/qt5/lib/libQt5WebKit.so.5
(gdb) ba
#0  0x00007ffff1811bee in JSC::DateInstance::calculateGregorianDateTimeUTC(JSC::ExecState*) const ()
    at /opt/qt5/lib/libQt5WebKit.so.5
#1  0x00007ffff1812150 in JSC::DateInstance::gregorianDateTimeUTC(JSC::ExecState*) const () at 
/opt/qt5/lib/libQt5WebKit.so.5
#2  0x00007ffff1812336 in JSC::formateDateInstance(JSC::ExecState*, JSC::DateTimeFormat, bool) () at 
/opt/qt5/lib/libQt5WebKit.so.5
#3  0x00007ffff1813360 in JSC::dateProtoFuncToGMTString(JSC::ExecState*) () at /opt/qt5/lib/libQt5WebKit.so.5
#4  0x00007fff8e2480c8 in  ()
#5  0x00007fffffffba90 in  ()
#6  0x00007ffff16faf39 in llint_entry () at /opt/qt5/lib/libQt5WebKit.so.5

**Comment by annulen** [comment]
Are you aware that you aren't building Release version? ASSERTs are not compiled in release

**Comment by annulen** [comment]
Such error can happen if NDEBUG is lost in CMAKE_CXX_FLAGS_RELEASE
