### ISSUE TITLE
Changes required for different pagesize on ppc64le.

### ISSUE THREAD

**Issue by asowani** [annulen/webkit#480]
Hi,

The pagesize value used in Source/JavaScriptCore/heap/CopiedBlock.h is 32KB. This is good for x86 based platforms, however creates issues when tried on ppc64le. This is because Power8/LE has default pagesize of 64KB. To accommodate this, I have modified the code with appropriate conditionals to have 64KB pagesize on ppc64le only, and to keep x86 value untouched. Also I have commented out an assert in Source/WebCore/loader/DocumentLoader.cpp which is not required on ppc64le (again with appropriate conditionals). I have all those changes available in my fork at https://github.com/asowani/webkit/

I would like to know if I have to create a PR here first and then the proposed changes will be reviewed or if they can be reviewed in the forked repo and then I should create a PR to merge those changes here.

Thanks,
Atul.

**Comment by annulen** [comment]
I'll cherry-pick 2b693daa76e19c88edd6984574fce1cfcccc6502 for CopiedBlock instead

**Comment by annulen** [comment]
>Also I have commented out an assert in Source/WebCore/loader/DocumentLoader.cpp which is not required on ppc64le (again with appropriate conditionals).

Does it break (debug) build f you leave this assert in place? If it fails at run time instead, this is fishy

**Comment by asowani** [comment]
Regarding the DocumentLoader.cpp change - I just confirmed that this particular change is not required. We are fine with assert enabled (even in debug mode). So we can ignore this change. Thanks!

**Comment by mitya57** [comment]
I am getting this crash on ppc64le with 5.212.0 alpha 2:
```
#0  0x00003fffb6115dc0 in bmalloc::SmallPage::ref(std::lock_guard<bmalloc::StaticMutex>&) (this=0x3fffac004e80)
    at ./Source/bmalloc/bmalloc/SmallPage.h:74
#1  0x00003fffb6115dc0 in bmalloc::Heap::<lambda(size_t&)>::operator() (lineNumber=<synthetic pointer>: 127, __closure=<synthetic pointer>)
    at ./Source/bmalloc/bmalloc/Heap.cpp:226
#2  0x00003fffb6115dc0 in bmalloc::Heap::allocateSmallBumpRangesByMetadata(std::lock_guard<bmalloc::StaticMutex>&, unsigned long, bmalloc::BumpAllocator&, bmalloc::FixedVector<bmalloc::BumpRange, 3ul>&) (this=0x3fffb7e675f8 <bmalloc::PerProcess<bmalloc::Heap>::s_memory>, lock=..., sizeClass=7, allocator=..., rangeCache=...) at ./Source/bmalloc/bmalloc/Heap.cpp:246
#3  0x00003fffb61123b4 in bmalloc::Heap::allocateSmallBumpRanges(std::lock_guard<bmalloc::StaticMutex>&, unsigned long, bmalloc::BumpAllocator&, bmalloc::FixedVector<bmalloc::BumpRange, 3ul>&) (rangeCache=..., allocator=..., sizeClass=<optimized out>, lock=..., this=<optimized out>)
    at ./Source/bmalloc/bmalloc/Heap.h:128
#4  0x00003fffb61123b4 in bmalloc::Allocator::refillAllocatorSlowCase(bmalloc::BumpAllocator&, unsigned long) (this=<optimized out>, allocator=..., sizeClass=<optimized out>) at ./Source/bmalloc/bmalloc/Allocator.cpp:146
#5  0x00003fffb61127b0 in bmalloc::Allocator::refillAllocator(bmalloc::BumpAllocator&, unsigned long) (sizeClass=<optimized out>, allocator=..., this=0x3fffb7f80810) at ./Source/bmalloc/bmalloc/Allocator.cpp:153
#6  0x00003fffb61127b0 in bmalloc::Allocator::allocateSlowCase(unsigned long) (this=0x3fffb7f80810, size=<optimized out>)
    at ./Source/bmalloc/bmalloc/Allocator.cpp:180
#7  0x00003fffb61135cc in bmalloc::Allocator::allocate(unsigned long) (size=64, this=<optimized out>) at ./Source/bmalloc/bmalloc/Allocator.h:85
#8  0x00003fffb61135cc in bmalloc::Cache::allocateSlowCaseNullCache(unsigned long) (size=64) at ./Source/bmalloc/bmalloc/Cache.cpp:66
#9  0x00003fffb37b16e8 in bmalloc::Cache::allocate(unsigned long) (size=64) at ./Source/bmalloc/bmalloc/Cache.h:78
#10 0x00003fffb37b16e8 in bmalloc::api::malloc(unsigned long) (size=64) at ./Source/bmalloc/bmalloc/bmalloc.h:43
#11 0x00003fffb37b16e8 in WTF::fastMalloc(unsigned long) (size=64) at ./Source/WTF/wtf/FastMalloc.cpp:193
#12 0x00003fffb4523ac0 in WTF::RefCounted<WebCore::UserContentController>::operator new(unsigned long) (size=64) at ./Source/WTF/wtf/RefCounted.h:141
#13 0x00003fffb4523ac0 in WebCore::UserContentController::create() () at ./Source/WebCore/page/UserContentController.cpp:54
#14 0x00003fffb30e06e4 in __static_initialization_and_destruction_0 (__priority=65535, __initialize_p=1)
    at ./Source/WebKit/qt/WebCoreSupport/QWebPageAdapter.cpp:209
#15 0x00003fffb30e06e4 in _GLOBAL__sub_I_QWebPageAdapter.cpp(void) () at ./Source/WebKit/qt/WebCoreSupport/QWebPageAdapter.cpp:1582
#16 0x00003fffb7fc32c0 in  () at /lib64/ld64.so.2
#17 0x00003fffb7fc3410 in  () at /lib64/ld64.so.2
#18 0x00003fffb7fb120c in  () at /lib64/ld64.so.2
```

@annulen Any reason why you have not cherry-picked 2b693daa76e19c88edd6984574fce1cfcccc6502 yet?
