### ISSUE TITLE
QPainter::end: Painter ended with 2 saved states

### ISSUE THREAD

**Issue by jurkov** [annulen/webkit#498]
If i use webkit-tp5 with the browser example from qt5.5.1 and compile it with 5.7.1 i get always the error QPainter::end: Painter ended with 2 saved states after i open https://api.onlyoffice.com/editors/demopreview.

If i use the qutebrowser i get the same error, but can browse continue.

Do you have any hint how to slove this?

**Comment by annulen** [comment]
This is related to #362 and #101. Temporary woraround may be to cherry-pick f45e84c4cb9b8837122eac3583d13f6f80f89ce5, but it introduces crash in other place

**Comment by jurkov** [comment]
I did the cherry-pick and got QPainter::end: Painter ended with 2 saved states 3 time like before

**Comment by annulen** [comment]
OK, looks like this bug has nothing to do with QPainter states. `https://doc.onlyoffice.com/2017-02-10-10-37/sdkjs/word/sdk-all.js:%2" "RangeError: Maximum call stack size exceeded` (printed to JS console) seems to be the culprit, it is constantly repeated.

**Comment by annulen** [comment]
* Disabling JIT has no effect
* WebKitGTK 2.12 finishes editor load successfully, so it's not upstream bug

**Comment by annulen** [comment]
```
#0  0x00007ffff501ffd0 in JSC::createStackOverflowError(JSC::ExecState*)@plt ()                                                                           
   from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/Release/lib/libQt5WebKit.so.5                                                                   
#1  0x00007ffff50bef11 in JSC::ParserError::toErrorObject(JSC::JSGlobalObject*, JSC::SourceCode const&, int) ()                                           
   from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/Release/lib/libQt5WebKit.so.5                                                                   
#2  0x00007ffff50beb15 in JSC::ScriptExecutable::newCodeBlockFor(JSC::CodeSpecializationKind, JSC::JSFunction*, JSC::JSScope*, JSC::JSObject*&) ()        
   from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/Release/lib/libQt5WebKit.so.5                                                                   
#3  0x00007ffff50bf31a in JSC::ScriptExecutable::prepareForExecutionImpl(JSC::ExecState*, JSC::JSFunction*, JSC::JSScope*, JSC::CodeSpecializationKind)   
    () from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/Release/lib/libQt5WebKit.so.5                                                               
#4  0x00007ffff52e0e54 in JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) () from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/Release/lib/libQt5WebKit.so.5                                                            
#5  0x00007ffff50bb001 in JSC::profiledCall(JSC::ExecState*, JSC::ProfilingReason, JSC::JSValue, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&, WTF::NakedPtr<JSC::Exception>&) () from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/Release/lib/libQt5WebKit.so.5                    
#6  0x00007ffff5e3079f in WebCore::JSEventListener::handleEvent(WebCore::ScriptExecutionContext*, WebCore::Event*) ()                                     
   from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/Release/lib/libQt5WebKit.so.5                                                                   
#7  0x00007ffff5cddbf7 in WebCore::EventTarget::fireEventListeners(WebCore::Event&, WebCore::EventTargetData*, WTF::Vector<WebCore::RegisteredEventListener, 1ul, WTF::CrashOnOverflow, 16ul>&) () from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/Release/lib/libQt5WebKit.so.5                             
#8  0x00007ffff5cd8db8 in WebCore::EventTarget::fireEventListeners(WebCore::Event&) ()                                                                    
   from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/Release/lib/libQt5WebKit.so.5                                                                   
#9  0x00007ffff5cc9ddd in WebCore::EventDispatcher::dispatchEvent(WebCore::Node*, WebCore::Event&) ()                                                     
   from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/Release/lib/libQt5WebKit.so.5                                                                   
#10 0x00007ffff5ced3a0 in WebCore::Node::dispatchEvent(WebCore::Event&) ()                                                                                
   from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/Release/lib/libQt5WebKit.so.5                                                                   
#11 0x00007ffff5c101b2 in WebCore::Editor::dispatchCPPEvent(WTF::AtomicString const&, WebCore::DataTransferAccessPolicy) ()                               
   from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/Release/lib/libQt5WebKit.so.5                                                                   
#12 0x00007ffff5c10314 in WebCore::Editor::canDHTMLCopy() () from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/Release/lib/libQt5WebKit.so.5         
#13 0x00007ffff5c7d710 in WebCore::enabledCopy(WebCore::Frame&, WebCore::Event*, WebCore::EditorCommandSource) ()                                         
   from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/Release/lib/libQt5WebKit.so.5                                                                   
#14 0x00007ffff5c29216 in WebCore::Editor::Command::isEnabled(WebCore::Event*) const ()                                                                   
   from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/Release/lib/libQt5WebKit.so.5                                                                   
#15 0x00007ffff507c95a in QWebPageAdapter::updateActionInternal(QWebPageAdapter::MenuAction, char const*, bool*, bool*) ()                                
   from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/Release/lib/libQt5WebKit.so.5                                                                   
#16 0x00007ffff725546a in QWebPagePrivate::updateAction(QWebPage::WebAction) ()                                                                           
   from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/Release/lib/libQt5WebKitWidgets.so.5                                                            
#17 0x00007ffff7255b5b in QWebPagePrivate::updateEditorActions() ()                                                                                       
   from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/Release/lib/libQt5WebKitWidgets.so.5                                                            
#18 0x00007ffff7257e99 in QWebPagePrivate::respondToChangedSelection() ()                                                                                 
   from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/Release/lib/libQt5WebKitWidgets.so.5                                                            
#19 0x00007ffff5059983 in WebCore::EditorClientQt::respondToChangedSelection(WebCore::Frame*) ()                                                          
   from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/Release/lib/libQt5WebKit.so.5
#20 0x00007ffff5c2c528 in WebCore::FrameSelection::setSelectionWithoutUpdatingAppearance(WebCore::VisibleSelection const&, unsigned int, WebCore::FrameSelection::CursorAlignOnScroll, WebCore::TextGranularity) () from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/Release/lib/libQt5WebKit.so.5
#21 0x00007ffff5c18dee in WebCore::FrameSelection::setSelection(WebCore::VisibleSelection const&, unsigned int, WebCore::AXTextStateChangeIntent, WebCore::FrameSelection::CursorAlignOnScroll, WebCore::TextGranularity) () from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/Release/lib/libQt5WebKit.so.5
#22 0x00007ffff5c2ab62 in WebCore::FrameSelection::moveTo(WebCore::Range const*) ()
   from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/Release/lib/libQt5WebKit.so.5
#23 0x00007ffff6356dcf in WebCore::jsDOMSelectionPrototypeFunctionAddRange(JSC::ExecState*) ()
   from /mnt/ssd2/WebKit/WebKit-new-qt-stable/WebKitBuild/Release/lib/libQt5WebKit.so.5
```

**Comment by annulen** [comment]
Use this patch for now:
```diff
diff --git a/Source/WebKit/qt/WebCoreSupport/EditorClientQt.cpp b/Source/WebKit/qt/WebCoreSupport/EditorClientQt.cpp
index f7316f71790..e7f90c0a9d5 100644
--- a/Source/WebKit/qt/WebCoreSupport/EditorClientQt.cpp
+++ b/Source/WebKit/qt/WebCoreSupport/EditorClientQt.cpp
@@ -204,7 +204,9 @@ void EditorClientQt::respondToChangedSelection(Frame* frame)
     if (supportsGlobalSelection() && frame->selection().isRange())
         Pasteboard::createForGlobalSelection()->writeSelection(*frame->selection().toNormalizedRange().get(), frame->editor().canSmartCopyOrDelete(), *fr
ame);
 
-    m_page->respondToChangedSelection();
+    RunLoop::main().dispatch([this]() {
+        m_page->respondToChangedSelection();
+    });
     if (!frame->editor().ignoreCompositionSelectionChange())
         emit m_page->microFocusChanged();
 }
```

**Comment by jurkov** [comment]
Thank you for your help! At least this bug is sloved. But it still can't load https://api.onlyoffice.com/editors/demopreview :-( Could you load and edit the text?
