### ISSUE TITLE
Assistant crashes after pressing "Qt 5.9" link

### ISSUE THREAD

**Issue by volkov0aa** [annulen/webkit#565]
Looks like https://bugs.webkit.org/show_bug.cgi?id=147870

```
#0  0x00007ffff31ed51c in WTFCrash () at ./Source/WTF/wtf/Assertions.cpp:322`
#1  0x00007ffff3d3bbf3 in WebCore::computeFreshnessLifetimeForHTTPFamily (response=..., responseTime=...) at ./Source/WebCore/platform/network/CacheValidation.cpp:110
#2  0x00007ffff3d3bc9f in WebCore::updateRedirectChainStatus (redirectChainCacheStatus=..., response=...) at ./Source/WebCore/platform/network/CacheValidation.cpp:153
#3  0x00007ffff3b33a48 in WebCore::CachedResource::redirectReceived (this=this@entry=0x7fffd85e5200, request=..., response=...) at ./Source/WebCore/loader/cache/CachedResource.cpp:403
#4  0x00007ffff3b2e9c6 in WebCore::CachedRawResource::redirectReceived (this=0x7fffd85e5200, request=..., response=...) at ./Source/WebCore/loader/cache/CachedRawResource.cpp:175
#5  0x00007ffff3b09c50 in WebCore::SubresourceLoader::willSendRequestInternal (this=0x7fff90c85a00, newRequest=..., redirectResponse=...)
    at ./Source/WebCore/loader/SubresourceLoader.cpp:203
#6  0x00007ffff3e7c88a in WebCore::QNetworkReplyHandler::redirect (this=this@entry=0x555555e1fd30, response=..., redirection=...)
    at ./Source/WebCore/platform/network/qt/QNetworkReplyHandler.cpp:686
#7  0x00007ffff3e7d0ff in WebCore::QNetworkReplyHandler::sendResponseIfNeeded (this=0x555555e1fd30) at ./Source/WebCore/platform/network/qt/QNetworkReplyHandler.cpp:611
#8  0x00007ffff3e7b05a in WebCore::QNetworkReplyHandlerCallQueue::flush (this=this@entry=0x555555e1fd68) at ./Source/WebCore/platform/network/qt/QNetworkReplyHandler.cpp:258
#9  0x00007ffff3e7dc46 in WebCore::QNetworkReplyHandlerCallQueue::flush (this=0x555555e1fd68) at ./Source/WebCore/platform/network/qt/QNetworkReplyHandler.cpp:252
#10 WebCore::QNetworkReplyHandlerCallQueue::unlock (this=0x555555e1fd68) at ./Source/WebCore/platform/network/qt/QNetworkReplyHandler.cpp:238
#11 WebCore::QueueLocker::~QueueLocker (this=<synthetic pointer>, __in_chrg=<optimized out>) at ./Source/WebCore/platform/network/qt/QNetworkReplyHandler.cpp:266
#12 WebCore::QNetworkReplyWrapper::receiveMetaData (this=<optimized out>) at ./Source/WebCore/platform/network/qt/QNetworkReplyHandler.cpp:335
#13 0x00007ffff17e6f47 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007ffff17f3536 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007ffff17e7f63 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007ffff78d221c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff78d9b71 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff17ba120 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007ffff180e6ee in QTimerInfoList::activateTimers() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007ffff180ef41 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007fffec9ff7f7 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007fffec9ffa60 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007fffec9ffb0c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007ffff180fa7f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00007ffff17b831a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007ffff17c0e64 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x000055555558609c in ?? ()
#28 0x00007ffff0e3d2b1 in __libc_start_main (main=0x555555585110, argc=1, argv=0x7fffffffe1b8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>,
    stack_end=0x7fffffffe1a8) at ../csu/libc-start.c:291
#29 0x00005555555867fa in ?? ()
```

**Comment by annulen** [comment]
Easy workaround is to use release build of QtWebKit. Assert on its own is harmless in this situation.

**Comment by volkov0aa** [comment]
Thanks, I'll try it.
