### ISSUE TITLE
Crash when starting video playback with gstreamer

### ISSUE THREAD

**Issue by annulen** [annulen/webkit#61]
QObject::startTimer: Timers cannot be started from another thread
ASSERTION FAILED: m_ID
../../../Source/WTF/wtf/qt/RunLoopQt.cpp(143) : void WTF::RunLoop::TimerBase::start(double, bool)

#0  WTFCrash () at ../../../Source/WTF/wtf/Assertions.cpp:322
#1  0x00007ffff395c5ca in WTF::RunLoop::TimerBase::start (this=0x89b430, nextFireInterval=0, repeat=false) at ../../../Source/WTF/wtf/qt/RunLoopQt.cpp:143
#2  0x00007ffff0290421 in WTF::RunLoop::TimerBase::startOneShot (this=0x89b430, interval=0) at ../../../Source/WTF/wtf/RunLoop.h:83
#3  0x00007ffff0298d04 in VideoRenderRequestScheduler::requestRender (this=0x89b420, sink=0x89b730, buffer=0x7fff6c52b270) at ../../../Source/WebCore/platform/graphics/gstreamer/VideoSinkGStreamer.cpp:119
#4  0x00007ffff0298155 in webkitVideoSinkRender (baseSink=0x89b730, buffer=0x7fff6c52b270) at ../../../Source/WebCore/platform/graphics/gstreamer/VideoSinkGStreamer.cpp:271

**Comment by annulen** [comment]
Fixed
