### ISSUE TITLE
tst_qwebview segfaults on Debian

### ISSUE THREAD

**Issue by mitya57** [annulen/webkit#613]
As part of packaging Qt WebKit for Debian, I tried to enable tests running using ctest. This is what I get with `tst_qwebview` on amd64 (will probably happen on the other architectures too):
```
#0  0x00007ffff3ab2a09 in WebCore::SubresourceLoader::didReceiveDataOrBuffer(char const*, int, WTF::PassRefPtr<WebCore::SharedBuffer>, long long, WebCore::DataPayloadType) (this=0x7fffe4144a00, data=0x0, length=0, prpBuffer=0x80, encodedDataLength=0, dataPayloadType=DataPayloadBytes)
    at ../Source/WebCore/loader/SubresourceLoader.cpp:322
#1  0x00007ffff3ab2d55 in WebCore::SubresourceLoader::didReceiveBuffer(WTF::PassRefPtr<WebCore::SharedBuffer>, long long, WebCore::DataPayloadType) (this=0x0, buffer=0x0, encodedDataLength=4294967295, dataPayloadType=4294967295) at ../Source/WebCore/loader/SubresourceLoader.cpp:304
#2  0x00007ffff3aa5a8a in WebCore::ResourceLoader::didReceiveBuffer(WebCore::ResourceHandle*, WTF::PassRefPtr<WebCore::SharedBuffer>, int) (this=0x0, buffer=0x7fffde3e2000, encodedDataLength=128) at ../Source/WebCore/loader/ResourceLoader.cpp:638
#3  0x00007ffff3e349e9 in WebCore::QNetworkReplyHandler::forwardData() (this=0x555555ff91b0)
    at ../Source/WebCore/platform/network/qt/QNetworkReplyHandler.cpp:724
#4  0x00007ffff3e341ac in WebCore::QNetworkReplyHandlerCallQueue::flush() [clone .part.95] (this=0x555555ff91e8)
    at ../Source/WebCore/platform/network/qt/QNetworkReplyHandler.cpp:258
#5  0x00007ffff3e367a8 in WebCore::QNetworkReplyWrapper::emitMetaDataChanged() (this=0x555555ff7c80)
    at ../Source/WebCore/platform/network/qt/QNetworkReplyHandler.cpp:393
#6  0x00007ffff3e369f0 in WebCore::QNetworkReplyWrapper::receiveMetaData() (this=0x555555ff7c80)
    at ../Source/WebCore/platform/network/qt/QNetworkReplyHandler.cpp:342
#7  0x00007ffff09e3865 in QMetaObject::activate(QObject*, int, int, void**) (sender=0x555555aea760, signalOffset=<optimized out>, local_signal_index=<optimized out>, argv=<optimized out>) at kernel/qobject.cpp:3766
#8  0x00007ffff09e43d2 in QObject::event(QEvent*) (this=0x555555aea760, e=<optimized out>) at kernel/qobject.cpp:1246
#9  0x00007ffff172f46c in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=this@entry=0x555555783640, receiver=receiver@entry=0x555555aea760, e=e@entry=0x555555ffe760) at kernel/qapplication.cpp:3717
#10 0x00007ffff1736d34 in QApplication::notify(QObject*, QEvent*) (this=0x7fffffffe460, receiver=0x555555aea760, e=0x555555ffe760)
    at kernel/qapplication.cpp:3476
#11 0x00007ffff09b4d68 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x555555aea760, event=event@entry=0x555555ffe760)
    at kernel/qcoreapplication.cpp:1018
#12 0x00007ffff09b74dd in QCoreApplication::sendEvent(QObject*, QEvent*) (event=0x555555ffe760, receiver=<optimized out>)
    at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:233
#13 0x00007ffff09b74dd in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (receiver=receiver@entry=0x0, event_type=event_type@entry=0, data=0x5555557837b0) at kernel/qcoreapplication.cpp:1678
#14 0x00007ffff09b7a68 in QCoreApplication::sendPostedEvents(QObject*, int) (receiver=receiver@entry=0x0, event_type=event_type@entry=0)
    at kernel/qcoreapplication.cpp:1532
#15 0x00007ffff0a0ddd3 in postEventSourceDispatch(GSource*, GSourceFunc, gpointer) (s=s@entry=0x5555557b7d90) at kernel/qeventdispatcher_glib.cpp:276
#16 0x00007fffeb7e2f67 in g_main_dispatch (context=0x7fffd80016f0) at ../../../../glib/gmain.c:3148
#17 0x00007fffeb7e2f67 in g_main_context_dispatch (context=context@entry=0x7fffd80016f0) at ../../../../glib/gmain.c:3813
#18 0x00007fffeb7e31a0 in g_main_context_iterate (context=context@entry=0x7fffd80016f0, block=block@entry=0, dispatch=dispatch@entry=1, self=<optimized out>) at ../../../../glib/gmain.c:3886
#19 0x00007fffeb7e322c in g_main_context_iteration (context=0x7fffd80016f0, may_block=may_block@entry=0) at ../../../../glib/gmain.c:3947
#20 0x00007ffff0a0d3ff in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x5555557b80b0, flags=...)
    at kernel/qeventdispatcher_glib.cpp:423
#21 0x00007ffff09b4e71 in QCoreApplication::processEvents(QFlags<QEventLoop::ProcessEventsFlag>, int) (flags=..., maxtime=<optimized out>)
    at kernel/qcoreapplication.cpp:1236
#22 0x000055555555a7aa in tst_QWebView::crashTests() (this=0x0) at /usr/include/x86_64-linux-gnu/qt5/QtTest/qtestsystem.h:64
```

**Comment by drizt** [comment]
I got the same with 

```
#include <QApplication>
#include <QWebView>
#include <QWebSettings>
#include <QNetworkProxy>

int main(int argc, char *argv[])
{
    QApplication a(argc, argv);

    QWebView *view = new QWebView;
    view->load(QUrl("https://google.com"));
    view->show();

    QObject::connect(view->page(), &QWebPage::loadProgress, view, [=](int progress) {
        if (progress >= 90) {
            view->stop();
        }
    });

    return a.exec();
}

```
