### ISSUE TITLE
Crash on www.weather.com

### ISSUE THREAD

**Issue by herbmillerjr** [annulen/webkit#615]
Not sure what element on the page is causing it, but anytime I navigate to www.weather.com in either Otter Browser or QtTestBrowser it crashes once the page loads.

Backtrace:
```#0  0x00007ffff4767c55 in void WTF::StringImpl::copyChars<unsigned short>(unsigned short*, unsigned short const*, unsigned int) () from /usr/src/qt/qt5.x/lib/libQt5WebKit.so.5
#1  0x00007ffff4774a16 in JSC::stringProtoFuncReplace(JSC::ExecState*) () from /usr/src/qt/qt5.x/lib/libQt5WebKit.so.5
#2  0x00007fff9f6b3768 in ?? ()
#3  0x00007fffffffbcf0 in ?? ()
#4  0x00007ffff491d16f in llint_entry () from /usr/src/qt/qt5.x/lib/libQt5WebKit.so.5
Backtrace stopped: frame did not save the PC```

Do you want me to get a backtrace from a debug build? It looks different. Stops on an assertion failure.

**Comment by The-Compiler** [comment]
Duplicate of #562?

**Comment by annulen** [comment]
It doesn't crash here in release. In debug I get assertion failure

```
ASSERTION FAILED: !thisObject->structure(vm)->prototypeChainMayInterceptStoreTo(exec->vm(), propertyName)
../../Source/JavaScriptCore/runtime/JSObjectInlines.h(54) : static void JSC::JSObject::putInline(JSC::JSCell *, JSC::ExecState *, JSC::PropertyName, JSC::JSValue, JSC::PutPropertySlot &)
```

**Comment by annulen** [comment]
Indeed, it may be #562

**Comment by herbmillerjr** [comment]
I am using gcc-7. I'll recompile with gcc-6 and if it stops happening I'll close this out.

**Comment by herbmillerjr** [comment]
Repeated with gcc 6.3.0 with same result.

Just tried on MacOS with following setup:
Qt 5.9.2 from built from git
QtWebKit 5.212 built from git
Otter Browser built from git

Both Otter and QtTestBrowser crashed.

**Comment by annulen** [comment]
1. Is assertion failure that you see the same as mine?

2. Could you provide more verbose backtrace?

**Comment by herbmillerjr** [comment]
Looks like same assertion, yes. Initial output:

```
ASSERTION FAILED: !thisObject->structure(vm)->prototypeChainMayInterceptStoreTo(exec->vm(), propertyName)
/usr/src/qt/webkit-fresh/Source/JavaScriptCore/runtime/JSObjectInlines.h(54) : static void JSC::JSObject::putInline(JSC::JSCell*, JSC::ExecState*, JSC::PropertyName, JSC::JSValue, JSC::PutPropertySlot&)
1   0x7ffff1bff562 /usr/src/qt/qt5.x-debug/lib/libQt5WebKit.so.5(WTFCrash+0x1e) [0x7ffff1bff562]
2   0x7ffff10f9cac /usr/src/qt/qt5.x-debug/lib/libQt5WebKit.so.5(+0x8efcac) [0x7ffff10f9cac]
3   0x7ffff10ebfb7 /usr/src/qt/qt5.x-debug/lib/libQt5WebKit.so.5(_ZN3JSC8JSObject3putEPNS_6JSCellEPNS_9ExecStateENS_12PropertyNameENS_7JSValueERNS_15PutPropertySlotE+0x3b) [0x7ffff10ebfb7]
4   0x7ffff1081a77 /usr/src/qt/qt5.x-debug/lib/libQt5WebKit.so.5(+0x877a77) [0x7ffff1081a77]
5   0x7ffff1085a83 /usr/src/qt/qt5.x-debug/lib/libQt5WebKit.so.5(+0x87ba83) [0x7ffff1085a83]
6   0x7ffff1165269 /usr/src/qt/qt5.x-debug/lib/libQt5WebKit.so.5(+0x95b269) [0x7ffff1165269]
7   0x7ffff16b29c0 /usr/src/qt/qt5.x-debug/lib/libQt5WebKit.so.5(+0xea89c0) [0x7ffff16b29c0]
8   0x7ffff140397a /usr/src/qt/qt5.x-debug/lib/libQt5WebKit.so.5(+0xbf997a) [0x7ffff140397a]
warning: Could not find DWO CU CMakeFiles/WTF.dir/Assertions.cpp.dwo(0x98ac9363ca45408e) referenced by CU at offset 0x961c [in module /usr/src/qt/qt5.x-debug/lib/libQt5WebKit.so.5]

Thread 1 "otter-browser" received signal SIGSEGV, Segmentation fault.
0x00007ffff1bff567 in WTFCrash () at /usr/src/qt/webkit-fresh/Source/WTF/wtf/Assertions.cpp:322
322	    *(int *)(uintptr_t)0xbbadbeef = 0;
```

Backtrace:

```
warning: Could not find DWO CU CMakeFiles/JavaScriptCore.dir/runtime/JSObject.cpp.dwo(0x55190f6cef7d4eaa) referenced by CU at offset 0x17c4 [in module /usr/src/qt/qt5.x-debug/lib/libQt5WebKit.so.5]
#0  0x00007ffff1bff567 in WTFCrash () at /usr/src/qt/webkit-fresh/Source/WTF/wtf/Assertions.cpp:322
#1  0x00007ffff10f9cac in JSC::JSObject::putInline(JSC::JSCell*, JSC::ExecState*, JSC::PropertyName, JSC::JSValue, JSC::PutPropertySlot&) () at /usr/src/qt/webkit-fresh/Source/JavaScriptCore/runtime/JSObjectInlines.h:54
#2  0x00007ffff10ebfb7 in JSC::JSObject::put(JSC::JSCell*, JSC::ExecState*, JSC::PropertyName, JSC::JSValue, JSC::PutPropertySlot&) () at /usr/src/qt/webkit-fresh/Source/JavaScriptCore/runtime/JSObject.cpp:384
warning: Could not find DWO CU CMakeFiles/JavaScriptCore.dir/runtime/JSArrayBufferView.cpp.dwo(0x7f8c87cd7c8af5eb) referenced by CU at offset 0x134c [in module /usr/src/qt/qt5.x-debug/lib/libQt5WebKit.so.5]
#3  0x00007ffff1081a77 in JSC::JSArrayBufferView::put(JSC::JSCell*, JSC::ExecState*, JSC::PropertyName, JSC::JSValue, JSC::PutPropertySlot&) () at /usr/src/qt/webkit-fresh/Source/JavaScriptCore/runtime/JSArrayBufferView.cpp:164
warning: Could not find DWO CU CMakeFiles/JavaScriptCore.dir/runtime/JSDataView.cpp.dwo(0x916f6d2f4c62ea16) referenced by CU at offset 0x13e8 [in module /usr/src/qt/qt5.x-debug/lib/libQt5WebKit.so.5]
#4  0x00007ffff1085a83 in JSC::JSDataView::put(JSC::JSCell*, JSC::ExecState*, JSC::PropertyName, JSC::JSValue, JSC::PutPropertySlot&) () at /usr/src/qt/webkit-fresh/Source/JavaScriptCore/runtime/JSDataView.cpp:125
warning: Could not find DWO CU CMakeFiles/JavaScriptCore.dir/runtime/LiteralParser.cpp.dwo(0x8ebb32cf4ccea56e) referenced by CU at offset 0x1c70 [in module /usr/src/qt/qt5.x-debug/lib/libQt5WebKit.so.5]
#5  0x00007ffff1165269 in JSC::JSValue::put(JSC::ExecState*, JSC::PropertyName, JSC::JSValue, JSC::PutPropertySlot&) () at /usr/src/qt/webkit-fresh/Source/JavaScriptCore/runtime/JSCJSValueInlines.h:762
warning: Could not find DWO CU CMakeFiles/JavaScriptCore.dir/llint/LLIntSlowPaths.cpp.dwo(0x56698977ff64147) referenced by CU at offset 0x65c4 [in module /usr/src/qt/qt5.x-debug/lib/libQt5WebKit.so.5]
#6  0x00007ffff16b29c0 in llint_slow_path_put_by_val () at /usr/src/qt/webkit-fresh/Source/JavaScriptCore/llint/LLIntSlowPaths.cpp:753
#7  0x00007ffff140397a in llint_entry () at /usr/src/qt/webkit-fresh/Source/JavaScriptCore/runtime/RegExp.h:61
#8  0x00007ffff1406327 in llint_entry () at /usr/src/qt/webkit-fresh/Source/JavaScriptCore/runtime/RegExp.h:61
#9  0x00007ffff1406327 in llint_entry () at /usr/src/qt/webkit-fresh/Source/JavaScriptCore/runtime/RegExp.h:61
#10 0x00007fff9c05a60f in ?? ()
#11 0x00007fff678adca0 in ?? ()
#12 0x00007fff679f67d0 in ?? ()
#13 0x0000016e00000004 in ?? ()
#14 0x00007fff67905e80 in ?? ()
#15 0x00007fff678bf040 in ?? ()
#16 0x00007fff67905e80 in ?? ()
#17 0x00007fff679f45b0 in ?? ()
#18 0x00000000f0f7606c in ?? ()
#19 0x00007fff9bcf5818 in ?? ()
#20 0x00007fffffffad30 in ?? ()
#21 0x00007fff678bf040 in ?? ()
#22 0x00007fff678d9f00 in ?? ()
#23 0x00007fff678d9f00 in ?? ()
#24 0x00007ffff16b6488 in llint_slow_path_call () at /usr/src/qt/webkit-fresh/Source/JavaScriptCore/llint/LLIntSlowPaths.cpp:1244
#25 0x00007ffff1406327 in llint_entry () at /usr/src/qt/webkit-fresh/Source/JavaScriptCore/runtime/RegExp.h:61
#26 0x00007fff9c04dd09 in ?? ()
#27 0x00007fff678c3c80 in ?? ()
#28 0x00007fff679f7ee0 in ?? ()
#29 0x0000008200000004 in ?? ()
#30 0x00007fff679069c0 in ?? ()
#31 0x00007fff678dc2b0 in ?? ()
#32 0x00007fff679069c0 in ?? ()
#33 0x00007fff679f45b0 in ?? ()
#34 0x00000000f0f7606c in ?? ()
#35 0x00007fff9bd04458 in ?? ()
#36 0x00007fff679f7ee0 in ?? ()
#37 0x00007fff678dc2b0 in ?? ()
#38 0x00007fff9a5d3f70 in ?? ()
#39 0x00007fff679f7ee0 in ?? ()
#40 0x000000000000000a in ?? ()
#41 0x00007fff678dc2b0 in ?? ()
#42 0x00007fff9a577620 in ?? ()
#43 0x00007fff9a577620 in ?? ()
#44 0x00007fff9bd04348 in ?? ()
#45 0xffff000000000000 in ?? ()
#46 0xffff000000000002 in ?? ()
#47 0x00007fffffffae60 in ?? ()
#48 0x00007ffff1406327 in llint_entry () at /usr/src/qt/webkit-fresh/Source/JavaScriptCore/runtime/RegExp.h:61
Backtrace stopped: frame did not save the PC
```
