### ISSUE TITLE
designer-qt5 crash with QtWebKit 5.212.0 Alpha 2

### ISSUE THREAD

**Issue by hubslave** [annulen/webkit#728]
designer-qt5 (originally compiled against upstream qtwebkit 5.7.1) crashes on start with the following stack:

```
Application: designer (designer), signal: Segmentation fault
Using host libthread_db library "/lib64/libthread_db.so.1".
[Current thread is 1 (Thread 0x7f6819fa0740 (LWP 13718))]

Thread 6 (Thread 0x7f67d5bff700 (LWP 13730)):
#0  0x00007f6813150804 in g_mutex_unlock () at /usr/lib64/libglib-2.0.so.0
#1  0x00007f681310d376 in g_main_context_check () at /usr/lib64/libglib-2.0.so.0
#2  0x00007f681310d8f8 in  () at /usr/lib64/libglib-2.0.so.0
#3  0x00007f681310da5c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#4  0x00007f681768ac7b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/qt5/bin/../../libQt5Core.so.5
#5  0x00007f68176387ea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/qt5/bin/../../libQt5Core.so.5
#6  0x00007f681746d6ec in QThread::exec() () at /usr/lib64/qt5/bin/../../libQt5Core.so.5
#7  0x00007f6817472069 in  () at /usr/lib64/qt5/bin/../../libQt5Core.so.5
#8  0x00007f6816f4a684 in start_thread () at /lib64/libpthread.so.0
#9  0x00007f68163e6efd in clone () at /lib64/libc.so.6

Thread 5 (Thread 0x7f67d7dd7700 (LWP 13726)):
#0  0x00007f6813150804 in g_mutex_unlock () at /usr/lib64/libglib-2.0.so.0
#1  0x00007f681310d52a in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#2  0x00007f681310d9b8 in  () at /usr/lib64/libglib-2.0.so.0
#3  0x00007f681310da5c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#4  0x00007f681768ac7b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/qt5/bin/../../libQt5Core.so.5
#5  0x00007f68176387ea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/qt5/bin/../../libQt5Core.so.5
#6  0x00007f681746d6ec in QThread::exec() () at /usr/lib64/qt5/bin/../../libQt5Core.so.5
#7  0x00007f6817472069 in  () at /usr/lib64/qt5/bin/../../libQt5Core.so.5
#8  0x00007f6816f4a684 in start_thread () at /lib64/libpthread.so.0
#9  0x00007f68163e6efd in clone () at /lib64/libc.so.6

Thread 4 (Thread 0x7f67e4676700 (LWP 13723)):
#0  0x00007f6816f5036f in pthread_cond_wait@@GLIBC_2.3.2 () at /lib64/libpthread.so.0
#1  0x00007f6816c7a8ac in std::condition_variable::wait(std::unique_lock<std::mutex>&) () at /usr/lib64/qt5/bin/../../libstdc++.so.6
#2  0x00007f67ea6a2b61 in void std::_V2::condition_variable_any::wait<std::unique_lock<bmalloc::Mutex> >(std::unique_lock<bmalloc::Mutex>&) () at /usr/lib64/libQt5WebKit.so.5
#3  0x00007f67ea6a214e in void std::_V2::condition_variable_any::wait<std::unique_lock<bmalloc::Mutex>, bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>::threadRunLoop()::{lambda()#1}>(std::unique_lock<bmalloc::Mutex>&, bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>::threadRunLoop()::{lambda()#1}) () at /usr/lib64/libQt5WebKit.so.5
#4  0x00007f67ea6a16f6 in bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>::threadRunLoop() () at /usr/lib64/libQt5WebKit.so.5
#5  0x00007f67ea6a0c70 in bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>::threadEntryPoint(bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*) () at /usr/lib64/libQt5WebKit.so.5
#6  0x00007f67ea6a45de in void std::_Bind_simple<void (*(bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*))(bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) () at /usr/lib64/libQt5WebKit.so.5
#7  0x00007f67ea6a44f7 in std::_Bind_simple<void (*(bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*))(bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*)>::operator()() () at /usr/lib64/libQt5WebKit.so.5
#8  0x00007f67ea6a4466 in std::thread::_Impl<std::_Bind_simple<void (*(bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*))(bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*)> >::_M_run() () at /usr/lib64/libQt5WebKit.so.5
#9  0x00007f6816c7f900 in  () at /usr/lib64/qt5/bin/../../libstdc++.so.6
#10 0x00007f6816f4a684 in start_thread () at /lib64/libpthread.so.0
#11 0x00007f68163e6efd in clone () at /lib64/libc.so.6

Thread 3 (Thread 0x7f67fdba5700 (LWP 13722)):
#0  0x00007f68163db30d in poll () at /lib64/libc.so.6
#1  0x00007f681310d954 in  () at /usr/lib64/libglib-2.0.so.0
#2  0x00007f681310da5c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#3  0x00007f681768ac7b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/qt5/bin/../../libQt5Core.so.5
#4  0x00007f68176387ea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/qt5/bin/../../libQt5Core.so.5
#5  0x00007f681746d6ec in QThread::exec() () at /usr/lib64/qt5/bin/../../libQt5Core.so.5
#6  0x00007f680c38d495 in  () at /usr/lib64/qt5/plugins/platforms/../../../libQt5DBus.so.5
#7  0x00007f6817472069 in  () at /usr/lib64/qt5/bin/../../libQt5Core.so.5
#8  0x00007f6816f4a684 in start_thread () at /lib64/libpthread.so.0
#9  0x00007f68163e6efd in clone () at /lib64/libc.so.6

Thread 2 (Thread 0x7f680a6b3700 (LWP 13719)):
#0  0x00007f68163db30d in poll () at /lib64/libc.so.6
#1  0x00007f68106b1102 in  () at /usr/lib64/libxcb.so.1
#2  0x00007f68106b2c8f in xcb_wait_for_event () at /usr/lib64/libxcb.so.1
#3  0x00007f680f092dd9 in  () at /usr/lib64/qt5/plugins/platforms/../../../libQt5XcbQpa.so.5
#4  0x00007f6817472069 in  () at /usr/lib64/qt5/bin/../../libQt5Core.so.5
#5  0x00007f6816f4a684 in start_thread () at /lib64/libpthread.so.0
#6  0x00007f68163e6efd in clone () at /lib64/libc.so.6

Thread 1 (Thread 0x7f6819fa0740 (LWP 13718)):
[KCrash Handler]
#6  0x00007f67e8aee9bc in WTF::Ref<WebCore::Document>::get() const () at /usr/lib64/libQt5WebKit.so.5
#7  0x00007f67e8ad22c2 in WebCore::Range::ownerDocument() const () at /usr/lib64/libQt5WebKit.so.5
#8  0x00007f67e8e5b157 in WebCore::createMarkup(WebCore::Range const&, WTF::Vector<WebCore::Node*, 0ul, WTF::CrashOnOverflow, 16ul>*, WebCore::EAnnotateForInterchange, bool, WebCore::EAbsoluteURLs) () at /usr/lib64/libQt5WebKit.so.5
#9  0x00007f67e8ef3652 in WebCore::Range::toHTML() const () at /usr/lib64/libQt5WebKit.so.5
#10 0x00007f67e7c3c12a in QWebPageAdapter::selectedHtml() const () at /usr/lib64/libQt5WebKit.so.5
#11 0x00007f6819e42a62 in QWebPage::selectedHtml() const () at /usr/lib64/libQt5WebKitWidgets.so.5
#12 0x00007f6819e4c05a in QWebView::selectedHtml() const () at /usr/lib64/libQt5WebKitWidgets.so.5
#13 0x00007f6819e4d5ab in QWebView::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) () at /usr/lib64/libQt5WebKitWidgets.so.5
#14 0x00007f6819e4d8b7 in QWebView::qt_metacall(QMetaObject::Call, int, void**) () at /usr/lib64/libQt5WebKitWidgets.so.5
#15 0x00007f67ee730705 in KWebView::qt_metacall(QMetaObject::Call, int, void**) () at /usr/lib64/libKF5WebKit.so.5
#16 0x00007f6817646cde in QMetaProperty::read(QObject const*) const () at /usr/lib64/qt5/bin/../../libQt5Core.so.5
#17 0x00007f68193e0e8d in  () at /usr/lib64/qt5/bin/../../libQt5Designer.so.5
#18 0x00007f68193985c3 in QDesignerPropertySheet::metaProperty(int) const () at /usr/lib64/qt5/bin/../../libQt5Designer.so.5
#19 0x00007f681939b7ed in QDesignerPropertySheet::property(int) const () at /usr/lib64/qt5/bin/../../libQt5Designer.so.5
#20 0x00007f68193d697e in qdesigner_internal::WidgetDataBase::defaultPropertyValues(QString const&) () at /usr/lib64/qt5/bin/../../libQt5Designer.so.5
#21 0x00007f68193d6c07 in qdesigner_internal::WidgetDataBase::grabDefaultPropertyValues() () at /usr/lib64/qt5/bin/../../libQt5Designer.so.5
#22 0x0000000000438623 in  ()
#23 0x000000000043117d in  ()
#24 0x000000000041fbd3 in  ()
#25 0x00007f68163007d0 in __libc_start_main () at /lib64/libc.so.6
#26 0x000000000041fc89 in  ()
```

(Feel free to close if this is irrelevant)

**Comment by annulen** [comment]
This should be fixed by 0e75f3272d149bc64899c161f150eb341a2417af

Please use tip of 5.212 branch or binary snapshots from http://download.qt.io/snapshots/ci/qtwebkit/5.212/latest/qtwebkit/ (the latter requires Qt 5.10.0 official binaries)
