### ISSUE TITLE
Assertion failed with Otter browser

### ISSUE THREAD

**Issue by paradogz** [annulen/webkit#742]
I saw two asserts today running Otter 0.9.96. Are these webkit or application issues?

# 1
```
ASSERTION FAILED: !isUndefined()
qtwebkit-5.212.0-alpha2/Source/WebCore/platform/Length.h(369) : bool WebCore::Length::isZero() const
#0  0x00007fffefec0917 in WTFCrash () at /usr/lib64/libQt5WebKit.so.5
#1  0x00007fffeff31246 in WebCore::Length::isZero() const () at /usr/lib64/libQt5WebKit.so.5
#2  0x00007fffeff313ff in WebCore::Length::blend(WebCore::Length const&, double) const () at /usr/lib64/libQt5WebKit.so.5
#3  0x00007ffff0c104ad in WebCore::blendFunc(WebCore::AnimationBase const*, WebCore::Length const&, WebCore::Length const&, double) ()
    at /usr/lib64/libQt5WebKit.so.5
#4  0x00007ffff0c2788e in WebCore::LengthPropertyWrapper<WebCore::Length>::blend(WebCore::AnimationBase const*, WebCore::RenderStyle*, WebCore::RenderStyle const*, WebCore::RenderStyle const*, double) const () at /usr/lib64/libQt5WebKit.so.5
#5  0x00007ffff0c16091 in WebCore::CSSPropertyAnimation::blendProperties(WebCore::AnimationBase const*, WebCore::CSSPropertyID, WebCore::RenderStyle*, WebCore::RenderStyle const*, WebCore::RenderStyle const*, double) () at /usr/lib64/libQt5WebKit.so.5
#6  0x00007ffff0c334a5 in WebCore::ImplicitAnimation::animate(WebCore::CompositeAnimation*, WebCore::RenderElement*, WebCore::RenderStyle const*, WebCore::RenderStyle*, WTF::RefPtr<WebCore::RenderStyle>&) () at /usr/lib64/libQt5WebKit.so.5
#7  0x00007ffff0c2a6e6 in WebCore::CompositeAnimation::animate(WebCore::RenderElement&, WebCore::RenderStyle*, WebCore::RenderStyle&, WTF::Ref<WebCore::RenderStyle>&) () at /usr/lib64/libQt5WebKit.so.5
#8  0x00007ffff0c08791 in WebCore::AnimationController::updateAnimations(WebCore::RenderElement&, WebCore::RenderStyle&, WTF::Ref<WebCore::RenderStyle>&) () at /usr/lib64/libQt5WebKit.so.5
#9  0x00007ffff0d9a302 in WebCore::RenderElement::setAnimatableStyle(WTF::Ref<WebCore::RenderStyle>&&, WebCore::StyleDifference) ()
    at /usr/lib64/libQt5WebKit.so.5
#10 0x00007ffff0d98c25 in WebCore::Style::TreeResolver::resolveElement(WebCore::Element&) () at /usr/lib64/libQt5WebKit.so.5
#11 0x00007ffff0d995de in WebCore::Style::TreeResolver::resolveComposedTree() () at /usr/lib64/libQt5WebKit.so.5
#12 0x00007ffff0d99964 in WebCore::Style::TreeResolver::resolve(WebCore::Style::Change) () at /usr/lib64/libQt5WebKit.so.5
#13 0x00007ffff04eb81f in WebCore::Document::recalcStyle(WebCore::Style::Change) () at /usr/lib64/libQt5WebKit.so.5
#14 0x00007ffff04ebb37 in WebCore::Document::updateStyleIfNeeded() () at /usr/lib64/libQt5WebKit.so.5
#15 0x00007ffff0ba1f8b in WebCore::FrameView::layout(bool) () at /usr/lib64/libQt5WebKit.so.5
#16 0x00007ffff0ba6157 in WebCore::FrameView::updateContentsSize() () at /usr/lib64/libQt5WebKit.so.5
#17 0x00007ffff0c5ef8a in WebCore::ScrollView::updateScrollbars(WebCore::IntPoint const&) () at /usr/lib64/libQt5WebKit.so.5
#18 0x00007ffff0c60a0b in WebCore::ScrollView::setFrameRect(WebCore::IntRect const&) () at /usr/lib64/libQt5WebKit.so.5
#19 0x00007ffff0b9fc10 in WebCore::FrameView::setFrameRect(WebCore::IntRect const&) () at /usr/lib64/libQt5WebKit.so.5
#20 0x00007fffef27bd2a in WebCore::Widget::resize(WebCore::IntSize const&) () at /usr/lib64/libQt5WebKit.so.5
#21 0x00007fffef27b3a3 in QWebFrameAdapter::setViewportSize(QSize const&) () at /usr/lib64/libQt5WebKit.so.5
#22 0x00007ffff7f8e0bd in QWebPage::setViewportSize(QSize const&) const () at /usr/lib64/libQt5WebKitWidgets.so.5
#23 0x00007ffff7f8caba in QWebPage::setView(QWidget*) () at /usr/lib64/libQt5WebKitWidgets.so.5
#24 0x000000000086ab43 in Otter::QtWebKitWebWidget::createThumbnail(QSize const&) (this=0x422ee30, size=...)
    at /home/user/otter/src/modules/backends/web/qtwebkit/QtWebKitWebWidget.cpp:2181
#25 0x0000000000835a76 in Otter::WebContentsWidget::createThumbnail() (this=0x4227280)
    at /home/user/otter/src/modules/windows/web/WebContentsWidget.cpp:1420
#26 0x000000000072b0a8 in Otter::Window::createThumbnail() const (this=this@entry=0x1001800)
    at /home/user/otter/src/ui/Window.cpp:727
#27 0x00000000006e04ae in Otter::TabBarWidget::showPreview(int, int) (this=this@entry=0x104d700, index=1, delay=delay@entry=0)
    at /home/user/otter/src/ui/TabBarWidget.cpp:1305
#28 0x00000000006e069b in Otter::TabBarWidget::timerEvent(QTimerEvent*) (this=0x104d700, event=<optimized out>)
    at /home/user/otter/src/ui/TabBarWidget.cpp:672
#29 0x00007fffedb0115b in QObject::event(QEvent*) () at /usr/lib64/libQt5Core.so.5
#30 0x00007ffff64bb5c3 in QWidget::event(QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#31 0x00007ffff65fe473 in QTabBar::event(QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#32 0x00000000006e41f0 in Otter::TabBarWidget::event(QEvent*) (this=0x104d700, event=0x7fffffffd620)
    at /home/user/otter/src/ui/TabBarWidget.cpp:1822
#33 0x00007ffff647741c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#34 0x00007ffff647e836 in QApplication::notify(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#35 0x00007fffedad7278 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#36 0x00007fffedb26c3e in QTimerInfoList::activateTimers() () at /usr/lib64/libQt5Core.so.5
#37 0x00007fffedb27181 in  () at /usr/lib64/libQt5Core.so.5
#38 0x00007fffe7409787 in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#39 0x00007fffe74099b8 in  () at /usr/lib64/libglib-2.0.so.0
#40 0x00007fffe7409a5c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#41 0x00007fffedb27c5f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#42 0x00007fffedad57ea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#43 0x00007fffedadd81d in QCoreApplication::exec() () at /usr/lib64/libQt5Core.so.5
#44 0x0000000000560ff3 in main(int, char**) (argc=1, argv=<optimized out>) at /home/user/otter/src/main.cpp:217
```

# 2
```
ASSERTION FAILED: m_closed || !m_handshake
qtwebkit-5.212.0-alpha2/Source/WebCore/Modules/websockets/WebSocketChannel.cpp(229) : virtual void WebCore::WebSocketChannel::fail(const WTF::String&)
#0  0x00007fffefec0917 in WTFCrash () at /usr/lib64/libQt5WebKit.so.5
#1  0x00007ffff1774aa6 in WebCore::WebSocketChannel::fail(WTF::String const&) () at /usr/lib64/libQt5WebKit.so.5
#2  0x00007ffff14df79f in WebCore::WebSocket::suspend(WebCore::ActiveDOMObject::ReasonForSuspension) () at /usr/lib64/libQt5WebKit.so.5
#3  0x00007ffff053c6f1 in WebCore::ScriptExecutionContext::suspendActiveDOMObjects(WebCore::ActiveDOMObject::ReasonForSuspension) ()
    at /usr/lib64/libQt5WebKit.so.5
#4  0x00007ffff04ed5d7 in WebCore::Document::suspendActiveDOMObjects(WebCore::ActiveDOMObject::ReasonForSuspension) ()
    at /usr/lib64/libQt5WebKit.so.5
#5  0x00007ffff04f58ba in WebCore::Document::suspend(WebCore::ActiveDOMObject::ReasonForSuspension) () at /usr/lib64/libQt5WebKit.so.5
#6  0x00007ffff15027a3 in WebCore::CachedFrame::CachedFrame(WebCore::Frame&) () at /usr/lib64/libQt5WebKit.so.5
#7  0x00007ffff1504e1d in std::_Unique_if<WebCore::CachedFrame>::_Single_object std::make_unique<WebCore::CachedFrame, WebCore::MainFrame&>(WebCore::MainFrame&) () at /usr/lib64/libQt5WebKit.so.5
#8  0x00007ffff1504a61 in WebCore::CachedPage::CachedPage(WebCore::Page&) () at /usr/lib64/libQt5WebKit.so.5
#9  0x00007ffff09a03f8 in std::_Unique_if<WebCore::CachedPage>::_Single_object std::make_unique<WebCore::CachedPage, WebCore::Page&>(WebCore::Page&) () at /usr/lib64/libQt5WebKit.so.5
#10 0x00007ffff099f926 in WebCore::PageCache::addIfCacheable(WebCore::HistoryItem&, WebCore::Page*) () at /usr/lib64/libQt5WebKit.so.5
#11 0x00007ffff0aa61bd in WebCore::FrameLoader::commitProvisionalLoad() () at /usr/lib64/libQt5WebKit.so.5
#12 0x00007ffff0a82747 in WebCore::DocumentLoader::commitIfReady() () at /usr/lib64/libQt5WebKit.so.5
#13 0x00007ffff0a84c34 in WebCore::DocumentLoader::commitLoad(char const*, int) () at /usr/lib64/libQt5WebKit.so.5
#14 0x00007ffff0a85299 in WebCore::DocumentLoader::dataReceived(WebCore::CachedResource*, char const*, int) ()
    at /usr/lib64/libQt5WebKit.so.5
#15 0x00007ffff0b02669 in WebCore::CachedRawResource::notifyClientsDataWasReceived(char const*, unsigned int) ()
    at /usr/lib64/libQt5WebKit.so.5
#16 0x00007ffff0b02380 in WebCore::CachedRawResource::addDataBuffer(WebCore::SharedBuffer&) () at /usr/lib64/libQt5WebKit.so.5
#17 0x00007ffff0ae263c in WebCore::SubresourceLoader::didReceiveDataOrBuffer(char const*, int, WTF::PassRefPtr<WebCore::SharedBuffer>, long long, WebCore::DataPayloadType) () at /usr/lib64/libQt5WebKit.so.5
#18 0x00007ffff0ae2436 in WebCore::SubresourceLoader::didReceiveBuffer(WTF::PassRefPtr<WebCore::SharedBuffer>, long long, WebCore::DataPayloadType) () at /usr/lib64/libQt5WebKit.so.5
#19 0x00007ffff0ade56e in WebCore::ResourceLoader::didReceiveBuffer(WebCore::ResourceHandle*, WTF::PassRefPtr<WebCore::SharedBuffer>, int) () at /usr/lib64/libQt5WebKit.so.5
#20 0x00007ffff0e76307 in WebCore::QNetworkReplyHandler::forwardData() () at /usr/lib64/libQt5WebKit.so.5
#21 0x00007ffff0e73b3c in WebCore::QNetworkReplyHandlerCallQueue::flush() () at /usr/lib64/libQt5WebKit.so.5
#22 0x00007ffff0e738d8 in WebCore::QNetworkReplyHandlerCallQueue::unlock() () at /usr/lib64/libQt5WebKit.so.5
#23 0x00007ffff0e7772b in WebCore::QueueLocker::~QueueLocker() () at /usr/lib64/libQt5WebKit.so.5
#24 0x00007ffff0e7456b in WebCore::QNetworkReplyWrapper::emitMetaDataChanged() () at /usr/lib64/libQt5WebKit.so.5
#25 0x00007ffff0e74360 in WebCore::QNetworkReplyWrapper::receiveSniffedMIMEType() () at /usr/lib64/libQt5WebKit.so.5
#26 0x00007ffff0e74270 in WebCore::QNetworkReplyWrapper::receiveMetaData() () at /usr/lib64/libQt5WebKit.so.5
#27 0x00007ffff0e76ffc in WebCore::QNetworkReplyWrapper::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
    at /usr/lib64/libQt5WebKit.so.5
#28 0x00007fffedb00371 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib64/libQt5Core.so.5
#29 0x00007fffedfa0a16 in  () at /usr/lib64/libQt5Network.so.5
#30 0x00007fffee037880 in  () at /usr/lib64/libQt5Network.so.5
#31 0x00007fffedb011a1 in QObject::event(QEvent*) () at /usr/lib64/libQt5Core.so.5
#32 0x00007ffff647741c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#33 0x00007ffff647e836 in QApplication::notify(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#34 0x00007fffedad7278 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#35 0x00007fffedad986b in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib64/libQt5Core.so.5
#36 0x00007fffedb27853 in  () at /usr/lib64/libQt5Core.so.5
#37 0x00007fffe7409787 in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#38 0x00007fffe74099b8 in  () at /usr/lib64/libglib-2.0.so.0
#39 0x00007fffe7409a5c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#40 0x00007fffedb27c5f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#41 0x00007fffedad57ea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#42 0x00007fffedadd81d in QCoreApplication::exec() () at /usr/lib64/libQt5Core.so.5
#43 0x0000000000560ff3 in main(int, char**) (argc=1, argv=<optimized out>) at /home/user/otter/src/main.cpp:217
```

**Comment by annulen** [comment]
You are using debug build with enabled assertions. It may crash.
