### ISSUE TITLE
Random crash when destroying web surface

### ISSUE THREAD

**Issue by sergey-borovkov** [annulen/webkit#785]
Happens when QML's WebSurface is destroyed. Seems to be a race condition.
Web surface was destroyed right before that. And there is a warning in the logs above:

"Error sending IPC message: Connection reset by peer"

Thread 28 "QThread" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 1673]
0x758da97c in QSocketNotifier::setEnabled () from /home/pi/squashfs-root/viewer/usr/lib/libQt5Core.so.5
(gdb) bt
#0  0x758da97c in QSocketNotifier::setEnabled () from /home/pi/squashfs-root/viewer/usr/lib/libQt5Core.so.5
#1  0x6a4c4eac in IPC::Connection::readyReadHandler () from /home/pi/squashfs-root/viewer/usr/lib/libQt5WebKit.so.5
#2  0x68ff61d0 in WTF::WorkQueue::WorkItemQt::qt_static_metacall () from /home/pi/squashfs-root/viewer/usr/lib/libQt5WebKit.so.5
#3  0x758c7060 in QMetaCallEvent::placeMetaCall () from /home/pi/squashfs-root/viewer/usr/lib/libQt5Core.so.5
#4  0x758cc838 in QObject::event () from /home/pi/squashfs-root/viewer/usr/lib/libQt5Core.so.5
#5  0x758907ac in QCoreApplicationPrivate::notify_helper () from /home/pi/squashfs-root/viewer/usr/lib/libQt5Core.so.5
#6  0x75890850 in doNotify () from /home/pi/squashfs-root/viewer/usr/lib/libQt5Core.so.5
#7  0x75890980 in QCoreApplication::notifyInternal2 () from /home/pi/squashfs-root/viewer/usr/lib/libQt5Core.so.5
#8  0x758940c0 in QCoreApplicationPrivate::sendPostedEvents () from /home/pi/squashfs-root/viewer/usr/lib/libQt5Core.so.5
#9  0x758fcdb4 in postEventSourceDispatch () from /home/pi/squashfs-root/viewer/usr/lib/libQt5Core.so.5
#10 0x76b7845c in g_main_context_dispatch () from /home/pi/squashfs-root/viewer/usr/lib/libglib-2.0.so.0
#11 0x76b786a4 in g_main_context_iterate () from /home/pi/squashfs-root/viewer/usr/lib/libglib-2.0.so.0
#12 0x76b787a4 in g_main_context_iteration () from /home/pi/squashfs-root/viewer/usr/lib/libglib-2.0.so.0
#13 0x758fbba0 in QEventDispatcherGlib::processEvents () from /home/pi/squashfs-root/viewer/usr/lib/libQt5Core.so.5
#14 0x7588dacc in QEventLoop::processEvents () from /home/pi/squashfs-root/viewer/usr/lib/libQt5Core.so.5
#15 0x7588e140 in QEventLoop::exec () from /home/pi/squashfs-root/viewer/usr/lib/libQt5Core.so.5
#16 0x7569c534 in QThread::exec () from /home/pi/squashfs-root/viewer/usr/lib/libQt5Core.so.5
#17 0x756a386c in QThreadPrivate::start () from /home/pi/squashfs-root/viewer/usr/lib/libQt5Core.so.5
#18 0x755a3060 in start_thread () from /home/pi/squashfs-root/viewer/lib/libpthread.so.0
#19 0x753ee300 in ?? () from /home/pi/squashfs-root/viewer/lib/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)

**Comment by sergey-borovkov** [comment]
Crash seems to be happening in the 
```
        SocketNotifierResourceGuard(QSocketNotifier* socketNotifier)
            : m_socketNotifier(socketNotifier)
        {
            m_socketNotifier.data()->setEnabled(false);
        }
```

Not sure if it's trying to access the invalid pointer or just nullptr.

**Comment by sergey-borovkov** [comment]
Adding if (m_socketNotifier) to the constructor fixes the crash. But then it leaks the threads.

**Comment by annulen** [comment]
Seems like it's caused by change in multiprocess model. Old QtWebKit was using one WebProcess per UIProcess, while new branch uses multiple WebProcess'es (and default value seems to be UINT_MAX, i.e. separate WebProcess for each WebView). Following things need to be done
* Change default behavior to using single WebProcess (to match behavior of previous versions)
* Add API to set process number limit
* Fix Qt-specific code (probably in IPC) which breaks when we have > 1 WebProcess
